//! RISC-V entry point — reset vector and early init.
//!
//! Provides the `_start` symbol placed at the reset vector by the linker script.
//! Sets up the stack, clears BSS, and jumps to `fstart_main`.

use core::arch::global_asm;

global_asm!(
    r#"
    .section .text.entry
    .global _start
_start:
    // Save boot arguments from QEMU before any register is clobbered.
    // QEMU RISC-V virt passes: a0 = mhartid, a1 = DTB address.
    //
    // Following coreboot's approach (src/arch/riscv/bootblock.S): save DTB
    // in the mscratch CSR which is immune to stack overflow. The hart ID
    // can always be re-read from mhartid.
    csrw mscratch, a1

    // Set up stack pointer (grows downward)
    la sp, _stack_top

    // Copy .data initializers from ROM to RAM.
    // _data_load = LMA (ROM), _data_start/_data_end = VMA (RAM).
    la t0, _data_load
    la t1, _data_start
    la t2, _data_end
1:
    bgeu t1, t2, 2f
    ld t3, 0(t0)
    sd t3, 0(t1)
    addi t0, t0, 8
    addi t1, t1, 8
    j 1b
2:
    // Clear BSS section
    la t0, _bss_start
    la t1, _bss_end
3:
    bgeu t0, t1, 4f
    sd zero, 0(t0)
    addi t0, t0, 8
    j 3b
4:
    // Jump to Rust entry point
    call fstart_main
    // Should never return; spin if it does
3:
    wfi
    j 3b
    "#
);

extern "Rust" {
    /// Rust entry point — generated by fstart-stage from board.ron capabilities.
    #[allow(dead_code)]
    fn fstart_main() -> !;
}
