//! RISC-V entry point for Allwinner D1 sunxi SoCs.
//!
//! The D1 BROM loads the eGON image into SRAM at `0x0002_0000` and jumps
//! to offset 0x00. Unlike AArch64 sunxi SoCs, the D1 starts directly in
//! RISC-V mode (M-mode) — no RMR switch is needed.
//!
//! ## T-Head C906 CSR initialization
//!
//! The C906 has custom machine-mode CSRs that control caches, memory
//! attributes, and branch prediction. These **must** be configured before
//! any MMIO access, otherwise the D-cache may swallow writes to device
//! registers (the default memory attributes after BROM may treat all
//! memory as cacheable). Both oreboot and U-Boot set these CSRs as the
//! very first instructions after entry.
//!
//! | CSR     | Addr   | Purpose                                       |
//! |---------|--------|-----------------------------------------------|
//! | MXSTATUS| 0x7C0  | T-Head ISA extensions, MAEE, unaligned access |
//! | MHCR    | 0x7C1  | I/D-cache enable, write-back, branch predict  |
//! | MCOR    | 0x7C2  | Invalidate I-cache, D-cache, BTB, BHT         |
//! | MHINT   | 0x7C5  | D-cache prefetch, write-alloc policy           |
//!
//! ## Binary layout
//!
//! ```text
//! [0x00] RV64 `j _start` (eGON header, .head.text)
//! [0x04] eGON.BT0 magic + header (.head.egon, 92 bytes)
//! [0x60] _start (.text.entry):
//!          C906 CSR init, save BROM regs, set up stack, clear BSS,
//!          call fstart_main
//! ```
//!
//! The BROM passes the boot device type in the eGON header at offset 0x28
//! (boot_media field), which is read by `fstart_soc_sunxi::boot_device_at()`.

use core::arch::global_asm;

global_asm!(
    r#"
    .equ CSR_MXSTATUS, 0x7C0
    .equ CSR_MCOR, 0x7C2

    .section .text.entry
    .global _start
_start:
    // ---------------------------------------------------------------
    // T-Head C906 custom CSR initialization — MUST come first.
    //
    // Without this, the D-cache may cache MMIO writes (device memory
    // treated as normal cacheable), so UART writes never reach the
    // hardware.  Both oreboot and U-Boot do this before anything else.
    //
    // CSR addresses are T-Head vendor extensions, not standard RISC-V.
    // ---------------------------------------------------------------

    // Disable interrupts (MIE, SIE).
    csrw mie, zero

    // MXSTATUS (0x7C0): Enable T-Head ISA extensions + MAEE.
    //   bit 22 = TheadISAEE — enable T-Head custom instructions.
    //   bit 21 = MAEE (Memory Attribute Extension Enable) — required
    //            so PMA/page attributes control cacheability; without
    //            this the core may use default (cacheable) for MMIO.
    //
    // Read-modify-write: preserve bits the BROM may have set.
    // Matches oreboot start() exactly.
    li t1, 0x1 << 22 | 0x1 << 21
    csrs CSR_MXSTATUS, t1

    // MCOR (0x7C2): Invalidate I-cache, D-cache, BTB, BHT.
    //   Flushes any stale state left by the BROM so we start clean.
    //   0x30013 = IC + DC + BHT + BTB invalidate.
    // Matches oreboot start() exactly.
    li t2, 0x30013
    csrw CSR_MCOR, t2

    // NOTE: We intentionally do NOT write MHCR (0x7C1) or MHINT
    // (0x7C5) here. Oreboot omits them and works; the BROM leaves
    // these CSRs in a usable default state. Adding explicit cache-
    // enable (MHCR) and prefetch-hint (MHINT) writes was the
    // original fstart approach but diverged from the known-good
    // oreboot path. Keep it minimal until UART output is confirmed.

    // ---------------------------------------------------------------
    // Standard RISC-V entry: save regs, set up stack, clear BSS.
    // ---------------------------------------------------------------

    // The D1 BROM starts the C906 in M-mode.
    // a0 is not guaranteed to be hartid (unlike QEMU), but the D1
    // has only a single hart (hartid=0). Read from CSR to be safe.

    // Save any boot arguments before they're clobbered.
    // On D1, the BROM doesn't pass a DTB in a1 (unlike QEMU), but
    // we save it anyway for consistency with the QEMU entry point.
    csrw mscratch, a1

    // Set up stack pointer (grows downward)
    la sp, _stack_top

    // Copy .data initializers from ROM to RAM.
    la t0, _data_load
    la t1, _data_start
    la t2, _data_end
1:
    bgeu t1, t2, 2f
    ld t3, 0(t0)
    sd t3, 0(t1)
    addi t0, t0, 8
    addi t1, t1, 8
    j 1b
2:
    // Clear BSS section
    la t0, _bss_start
    la t1, _bss_end
3:
    bgeu t0, t1, 4f
    sd zero, 0(t0)
    addi t0, t0, 8
    j 3b
4:
    // Jump to Rust entry point.
    // a0 = handoff_ptr = 0 (no inter-stage handoff on first stage).
    li a0, 0
    call fstart_main
    // Should never return; spin if it does
5:
    wfi
    j 5b
    "#
);

extern "Rust" {
    /// Rust entry point — generated by fstart-stage from board.ron capabilities.
    ///
    /// `handoff_ptr` is the address of a serialized `StageHandoff` from a
    /// previous stage, or 0 if this is the first/only stage.
    #[allow(dead_code)]
    fn fstart_main(handoff_ptr: usize) -> !;
}
