//! S-mode entry point for stages booted via SBI firmware.
//!
//! When OpenSBI (or RustSBI) completes initialization, it `mret`s to the
//! address specified in `FwDynamicInfo.next_addr` in S-mode.  The SBI
//! convention passes:
//!   - `a0` = boot hart ID
//!   - `a1` = DTB address (physical, from the host/FDT)
//!
//! This entry point saves the DTB address in `sscratch` (accessible in
//! S-mode, unlike `mscratch`), sets up the stack, copies `.data`, clears
//! BSS, and jumps to `fstart_main`.
//!
//! No multi-hart parking is needed: OpenSBI boots only the designated
//! hart into S-mode; secondary harts stay in SBI until woken via HSM.

use core::arch::global_asm;

global_asm!(
    r#"
    .section .text.entry
    .global _start
_start:
    // Save DTB address (a1) in sscratch — the S-mode equivalent of
    // mscratch.  Readable later via boot_dtb_addr_smode().
    csrw sscratch, a1

    // Save hart ID (a0) to a BSS global — sscratch is already used for
    // DTB.  We must do this AFTER BSS clear, so stash in t6 for now.
    mv t6, a0

    // Set up stack pointer (grows downward)
    la sp, _stack_top

    // Copy .data initializers from ROM to RAM.
    // _data_load = LMA (ROM), _data_start/_data_end = VMA (RAM).
    la t0, _data_load
    la t1, _data_start
    la t2, _data_end
1:
    bgeu t1, t2, 2f
    ld t3, 0(t0)
    sd t3, 0(t1)
    addi t0, t0, 8
    addi t1, t1, 8
    j 1b
2:
    // Clear BSS section
    la t0, _bss_start
    la t1, _bss_end
3:
    bgeu t0, t1, 4f
    sd zero, 0(t0)
    addi t0, t0, 8
    j 3b
4:
    // Now store hart ID in BSS global (BSS is cleared above).
    la t0, _smode_hart_id
    sd t6, 0(t0)

    // Jump to Rust entry point.
    // a0 = handoff_ptr = 0 (boot parameters come from sscratch/BSS).
    li a0, 0
    call fstart_main
    // Should never return; fall through to park
    wfi
    j 4b

    .section .bss
    .balign 8
    .global _smode_hart_id
_smode_hart_id:
    .quad 0
    "#
);

extern "Rust" {
    /// Rust entry point — generated by fstart-stage from board.ron capabilities.
    #[allow(dead_code)]
    fn fstart_main(handoff_ptr: usize) -> !;
}
