[package]
name = "fstart-platform-qemu"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
host = []
stage = [
  "dep:fstart-stage",
  "dep:fstart-driver-uart",
]
x86_64 = ["fstart-arch/x86_64", "fstart-stage?/x86_64"]
riscv64 = ["fstart-arch/riscv64", "fstart-stage?/riscv64"]
aarch64 = ["fstart-arch/aarch64", "fstart-stage?/aarch64"]
armv7 = ["fstart-arch/armv7", "fstart-stage?/armv7"]
linux = ["fstart-stage?/linux"]
crabefi = ["fstart-stage?/crabefi"]
smbios = ["fstart-stage?/smbios"]

[dependencies]
fstart-core = { workspace = true }
fstart-arch = { workspace = true }
fstart-log = { workspace = true }
fstart-pci = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-driver-uart = { workspace = true, optional = true }
serde = { workspace = true }
ufmt = { workspace = true }
