//! Generate stage entry point code from board configuration.
//!
//! Given a BoardConfig (or a specific stage within it), this module emits
//! Rust source code for `fstart_main()` that:
//! 1. Instantiates drivers based on device declarations
//! 2. Calls capabilities in the declared order
//! 3. Halts or loops at the end

use fstart_types::{BoardConfig, Capability, DeviceConfig, StageLayout};

/// Generate the complete Rust source for a stage's main.rs.
///
/// This is the heart of fstart's "RON drives everything" philosophy.
/// The returned string is valid `#![no_std] #![no_main]` Rust source.
pub fn generate_stage_source(config: &BoardConfig, stage_name: Option<&str>) -> String {
    let mut out = String::new();

    // File header
    // Note: #![no_std] and #![no_main] are in the crate root (main.rs),
    // not here, because inner attributes must be at the crate root.
    out.push_str("// AUTO-GENERATED by fstart-codegen from board.ron\n");
    out.push_str("// DO NOT EDIT — changes will be overwritten.\n\n");

    // Pull in platform entry point (_start → fstart_main) and runtime (panic handler).
    // These are `use ... as _` so the linker sees the symbols even though Rust
    // code doesn't reference them directly.
    match config.platform.as_str() {
        "riscv64" => {
            out.push_str("extern crate fstart_platform_riscv64;\n");
        }
        "aarch64" => {
            out.push_str("extern crate fstart_platform_aarch64;\n");
        }
        p => {
            out.push_str(&format!("compile_error!(\"unsupported platform: {p}\");\n"));
        }
    }
    out.push_str("extern crate fstart_runtime;\n\n");
    out.push_str("use fstart_services::Console;\n\n");

    // Get capabilities for this stage
    let capabilities = match (&config.stages, stage_name) {
        (StageLayout::Monolithic(mono), _) => &mono.capabilities,
        (StageLayout::MultiStage(stages), Some(name)) => {
            if let Some(stage) = stages.iter().find(|s| s.name.as_str() == name) {
                &stage.capabilities
            } else {
                return format!("compile_error!(\"stage '{name}' not found in board config\");\n");
            }
        }
        (StageLayout::MultiStage(_), None) => {
            return "compile_error!(\"multi-stage board requires FSTART_STAGE_NAME\");\n"
                .to_string();
        }
    };

    // Generate fstart_main
    out.push_str("#[no_mangle]\n");
    out.push_str("pub extern \"Rust\" fn fstart_main() -> ! {\n");

    for cap in capabilities {
        match cap {
            Capability::ConsoleInit { device } => {
                generate_console_init(&mut out, device.as_str(), &config.devices);
            }
            Capability::SigVerify => {
                out.push_str("    // TODO: SigVerify capability\n");
            }
            Capability::MemoryInit => {
                out.push_str("    // TODO: MemoryInit capability\n");
            }
            Capability::DriverInit => {
                out.push_str("    // TODO: DriverInit capability\n");
            }
            Capability::FdtPrepare => {
                out.push_str("    // TODO: FdtPrepare capability\n");
            }
            Capability::PayloadLoad => {
                out.push_str("    // TODO: PayloadLoad capability\n");
            }
            Capability::StageLoad { next_stage } => {
                out.push_str(&format!(
                    "    // TODO: StageLoad capability (next: {next_stage})\n"
                ));
            }
        }
    }

    // Halt at end
    out.push_str("\n    // Stage complete — halt\n");
    match config.platform.as_str() {
        "riscv64" => out.push_str("    fstart_platform_riscv64::halt();\n"),
        "aarch64" => out.push_str("    fstart_platform_aarch64::halt();\n"),
        _ => out.push_str("    loop { core::hint::spin_loop(); }\n"),
    }

    out.push_str("}\n");
    out
}

/// Generate code to initialize a console from a device declaration.
fn generate_console_init(out: &mut String, device_name: &str, devices: &[DeviceConfig]) {
    let Some(dev) = devices.iter().find(|d| d.name.as_str() == device_name) else {
        out.push_str(&format!(
            "    compile_error!(\"device '{device_name}' not found\");\n"
        ));
        return;
    };

    match dev.driver.as_str() {
        "ns16550" => {
            let base = dev.resources.mmio_base.unwrap_or(0);
            let clock = dev.resources.clock_freq.unwrap_or(0);
            let baud = dev.resources.baud_rate.unwrap_or(115200);
            out.push_str("    // ConsoleInit: ns16550\n");
            out.push_str("    {\n");
            out.push_str(&format!(
                "        let uart = fstart_drivers::uart::ns16550::Ns16550::new({base:#x});\n"
            ));
            if clock > 0 && baud > 0 {
                out.push_str(&format!("        uart.init({clock}, {baud});\n"));
            }
            out.push_str(&format!(
                "        let _ = uart.write_line(\"[fstart] {device_name}: ns16550 console ready\");\n"
            ));
            // For now just let it go out of scope; later we'll wire it into StageContext
            out.push_str("    }\n");
        }
        "pl011" => {
            let base = dev.resources.mmio_base.unwrap_or(0);
            let clock = dev.resources.clock_freq.unwrap_or(0);
            let baud = dev.resources.baud_rate.unwrap_or(115200);
            out.push_str("    // ConsoleInit: pl011\n");
            out.push_str("    {\n");
            out.push_str(&format!(
                "        let uart = fstart_drivers::uart::pl011::Pl011::new({base:#x});\n"
            ));
            if clock > 0 && baud > 0 {
                out.push_str(&format!("        uart.init({clock}, {baud});\n"));
            }
            out.push_str(&format!(
                "        let _ = uart.write_line(\"[fstart] {device_name}: pl011 console ready\");\n"
            ));
            out.push_str("    }\n");
        }
        other => {
            out.push_str(&format!(
                "    compile_error!(\"unknown console driver: {other}\");\n"
            ));
        }
    }
}
