//! Generate stage entry point code from board configuration.
//!
//! Given a BoardConfig (or a specific stage within it), this module emits
//! Rust source code that:
//!
//! 1. Defines a `Devices` struct with one concrete typed field per device
//! 2. Defines a `StageContext` with service accessor methods
//! 3. Generates `fstart_main()` that constructs devices, runs capabilities
//!    in declared order, and halts
//!
//! See [docs/driver-model.md](../../../docs/driver-model.md).

use fstart_types::{BoardConfig, Capability, DeviceConfig, StageLayout};

/// Information about a known driver — maps RON driver name to Rust type path
/// and its config construction logic.
#[allow(dead_code)] // `services` used for validation in later phases
struct DriverInfo {
    /// RON driver name (e.g., "ns16550")
    name: &'static str,
    /// Rust module path (e.g., "fstart_drivers::uart::ns16550")
    module_path: &'static str,
    /// Rust type name (e.g., "Ns16550")
    type_name: &'static str,
    /// Rust config type name (e.g., "Ns16550Config")
    config_type: &'static str,
    /// Which service traits this driver implements
    services: &'static [&'static str],
}

/// Registry of known drivers.
const KNOWN_DRIVERS: &[DriverInfo] = &[
    DriverInfo {
        name: "ns16550",
        module_path: "fstart_drivers::uart::ns16550",
        type_name: "Ns16550",
        config_type: "Ns16550Config",
        services: &["Console"],
    },
    DriverInfo {
        name: "pl011",
        module_path: "fstart_drivers::uart::pl011",
        type_name: "Pl011",
        config_type: "Pl011Config",
        services: &["Console"],
    },
];

/// Look up driver info by RON driver name.
fn find_driver(name: &str) -> Option<&'static DriverInfo> {
    KNOWN_DRIVERS.iter().find(|d| d.name == name)
}

/// Generate the complete Rust source for a stage's main.rs.
///
/// This is the heart of fstart's "RON drives everything" philosophy.
/// The returned string is valid Rust source to be `include!()`d in the
/// `#![no_std] #![no_main]` crate root.
pub fn generate_stage_source(config: &BoardConfig, stage_name: Option<&str>) -> String {
    let mut out = String::new();

    // File header
    out.push_str("// AUTO-GENERATED by fstart-codegen from board.ron\n");
    out.push_str("// DO NOT EDIT — changes will be overwritten.\n\n");

    // Pull in platform entry point (_start -> fstart_main) and runtime (panic handler).
    let platform = config.platform.as_str();
    match platform {
        "riscv64" => {
            out.push_str("extern crate fstart_platform_riscv64;\n");
        }
        "aarch64" => {
            out.push_str("extern crate fstart_platform_aarch64;\n");
        }
        p => {
            out.push_str(&format!("compile_error!(\"unsupported platform: {p}\");\n"));
        }
    }
    out.push_str("extern crate fstart_runtime;\n\n");

    // Get capabilities for this stage
    let capabilities = match (&config.stages, stage_name) {
        (StageLayout::Monolithic(mono), _) => &mono.capabilities,
        (StageLayout::MultiStage(stages), Some(name)) => {
            if let Some(stage) = stages.iter().find(|s| s.name.as_str() == name) {
                &stage.capabilities
            } else {
                return format!("compile_error!(\"stage '{name}' not found in board config\");\n");
            }
        }
        (StageLayout::MultiStage(_), None) => {
            return "compile_error!(\"multi-stage board requires FSTART_STAGE_NAME\");\n"
                .to_string();
        }
    };

    // Collect all devices referenced by capabilities to determine what we need.
    // For now, generate structs for ALL declared devices.
    generate_imports(&mut out, &config.devices);
    generate_devices_struct(&mut out, &config.devices);
    generate_stage_context(&mut out, &config.devices);
    generate_fstart_main(&mut out, config, capabilities, platform);

    out
}

/// Emit `use` statements for all driver types needed by this board's devices.
fn generate_imports(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("use fstart_services::Console;\n");
    out.push_str("use fstart_services::device::Device;\n\n");

    // Collect unique driver modules
    let mut seen: Vec<&str> = Vec::new();
    for dev in devices {
        let drv_name = dev.driver.as_str();
        if !seen.contains(&drv_name) {
            if let Some(info) = find_driver(drv_name) {
                out.push_str(&format!(
                    "use {}::{{{}, {}}};\n",
                    info.module_path, info.type_name, info.config_type,
                ));
            }
            seen.push(drv_name);
        }
    }
    out.push('\n');
}

/// Emit the `Devices` struct — one concrete typed field per device.
fn generate_devices_struct(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("/// All devices for this board, with concrete types.\n");
    out.push_str("struct Devices {\n");
    for dev in devices {
        let field_name = dev.name.as_str();
        if let Some(info) = find_driver(dev.driver.as_str()) {
            out.push_str(&format!("    {field_name}: {},\n", info.type_name));
        } else {
            out.push_str(&format!("    // unknown driver: {}\n", dev.driver.as_str()));
        }
    }
    out.push_str("}\n\n");
}

/// Emit the `StageContext` struct with typed service accessors.
fn generate_stage_context(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("/// Stage context — provides typed access to services.\n");
    out.push_str("struct StageContext {\n");
    out.push_str("    devices: Devices,\n");
    out.push_str("}\n\n");

    out.push_str("impl StageContext {\n");

    // Find the first device providing each service type and generate an accessor.
    let service_types = ["Console", "BlockDevice", "Timer"];
    let accessor_names = ["console", "block_device", "timer"];
    let trait_names = ["Console", "BlockDevice", "Timer"];

    for (i, svc) in service_types.iter().enumerate() {
        if let Some(dev) = devices
            .iter()
            .find(|d| d.services.iter().any(|s| s.as_str() == *svc))
        {
            let field = dev.name.as_str();
            let accessor = accessor_names[i];
            let trait_name = trait_names[i];
            out.push_str("    #[inline]\n");
            out.push_str(&format!(
                "    fn {accessor}(&self) -> &(impl {trait_name} + '_) {{\n"
            ));
            out.push_str(&format!("        &self.devices.{field}\n"));
            out.push_str("    }\n\n");
        }
    }

    out.push_str("}\n\n");
}

/// Emit the `fstart_main()` function — device construction, capability
/// execution, and halt.
fn generate_fstart_main(
    out: &mut String,
    config: &BoardConfig,
    capabilities: &[Capability],
    platform: &str,
) {
    let halt_fn = match platform {
        "riscv64" => "fstart_platform_riscv64::halt()",
        "aarch64" => "fstart_platform_aarch64::halt()",
        _ => "loop { core::hint::spin_loop(); }",
    };

    out.push_str("#[no_mangle]\n");
    out.push_str("pub extern \"Rust\" fn fstart_main() -> ! {\n");

    // --- Phase 1: Construct all devices (bind phase) ---
    out.push_str("    // === Device construction (bind phase) ===\n");
    for dev in &config.devices {
        generate_device_construction(out, dev, halt_fn);
    }
    out.push('\n');

    // --- Phase 2: Execute capabilities in declared order ---
    out.push_str("    // === Capability execution ===\n");
    for cap in capabilities {
        match cap {
            Capability::ConsoleInit { device } => {
                generate_console_init(out, device.as_str(), &config.devices, halt_fn);
            }
            Capability::SigVerify => {
                out.push_str("    // TODO: SigVerify capability\n");
            }
            Capability::MemoryInit => {
                out.push_str("    // TODO: MemoryInit capability\n");
            }
            Capability::DriverInit => {
                out.push_str("    // TODO: DriverInit capability\n");
            }
            Capability::FdtPrepare => {
                out.push_str("    // TODO: FdtPrepare capability\n");
            }
            Capability::PayloadLoad => {
                out.push_str("    // TODO: PayloadLoad capability\n");
            }
            Capability::StageLoad { next_stage } => {
                out.push_str(&format!(
                    "    // TODO: StageLoad capability (next: {next_stage})\n"
                ));
            }
        }
    }

    // --- Phase 3: Build context and finalize ---
    out.push_str("\n    // === Build stage context ===\n");
    out.push_str("    let _ctx = StageContext {\n");
    out.push_str("        devices: Devices {\n");
    for dev in &config.devices {
        if find_driver(dev.driver.as_str()).is_some() {
            out.push_str(&format!("            {0}: {0},\n", dev.name.as_str()));
        }
    }
    out.push_str("        },\n");
    out.push_str("    };\n\n");

    // Halt
    out.push_str("    // Stage complete — halt\n");
    out.push_str(&format!("    {halt_fn};\n"));

    out.push_str("}\n");
}

/// Generate a device construction call using the `Device` trait.
fn generate_device_construction(out: &mut String, dev: &DeviceConfig, halt_fn: &str) {
    let name = dev.name.as_str();
    let drv_name = dev.driver.as_str();

    let Some(info) = find_driver(drv_name) else {
        out.push_str(&format!(
            "    compile_error!(\"unknown driver: {drv_name}\");\n"
        ));
        return;
    };

    out.push_str(&format!(
        "    let {name} = {}::new(&{} {{\n",
        info.type_name, info.config_type
    ));

    // Map Resources fields to config fields based on driver type.
    generate_config_fields(out, dev, info);

    out.push_str(&format!("    }}).unwrap_or_else(|_| {halt_fn});\n"));
}

/// Map RON Resources to driver-specific Config fields.
fn generate_config_fields(out: &mut String, dev: &DeviceConfig, info: &DriverInfo) {
    let res = &dev.resources;
    let name = dev.name.as_str();

    match info.name {
        "ns16550" | "pl011" => {
            // UART drivers need: base_addr, clock_freq, baud_rate
            if let Some(base) = res.mmio_base {
                out.push_str(&format!("        base_addr: {base:#x},\n"));
            } else {
                out.push_str(&format!(
                    "        base_addr: compile_error!(\"device '{name}' requires mmio_base\"),\n"
                ));
            }
            out.push_str(&format!(
                "        clock_freq: {},\n",
                res.clock_freq.unwrap_or(0)
            ));
            out.push_str(&format!(
                "        baud_rate: {},\n",
                res.baud_rate.unwrap_or(115200)
            ));
        }
        _ => {
            out.push_str(&format!(
                "        // TODO: config mapping for driver '{}'",
                info.name
            ));
        }
    }
}

/// Generate code for the ConsoleInit capability.
fn generate_console_init(
    out: &mut String,
    device_name: &str,
    devices: &[DeviceConfig],
    halt_fn: &str,
) {
    let Some(dev) = devices.iter().find(|d| d.name.as_str() == device_name) else {
        out.push_str(&format!(
            "    compile_error!(\"ConsoleInit references device '{device_name}' which is not declared\");\n"
        ));
        return;
    };

    let drv_name = dev.driver.as_str();
    let Some(_info) = find_driver(drv_name) else {
        out.push_str(&format!(
            "    compile_error!(\"device '{device_name}' uses unknown driver '{drv_name}'\");\n"
        ));
        return;
    };

    // Check that this device actually provides Console service
    if !dev.services.iter().any(|s| s.as_str() == "Console") {
        out.push_str(&format!(
            "    compile_error!(\"ConsoleInit requires Console service but device '{device_name}' does not provide it\");\n"
        ));
        return;
    }

    out.push_str(&format!("    // ConsoleInit: {drv_name}\n"));
    out.push_str(&format!(
        "    {device_name}.init().unwrap_or_else(|_| {halt_fn});\n"
    ));
    out.push_str(&format!(
        "    fstart_capabilities::console_ready(&{device_name}, \"{device_name}\", \"{drv_name}\");\n"
    ));
}
