//! Generate stage entry point code from board configuration.
//!
//! Given a BoardConfig (or a specific stage within it), this module emits
//! Rust source code that:
//!
//! 1. Defines a `Devices` struct with one concrete typed field per device
//! 2. Defines a `StageContext` with service accessor methods
//! 3. Generates `fstart_main()` that constructs devices, runs capabilities
//!    in declared order, and halts
//!
//! See [docs/driver-model.md](../../../docs/driver-model.md).

use fstart_types::{BoardConfig, Capability, DeviceConfig, StageLayout};

/// Information about a known driver — maps RON driver name to Rust type path
/// and its config construction logic.
struct DriverInfo {
    /// RON driver name (e.g., "ns16550")
    name: &'static str,
    /// Rust module path (e.g., "fstart_drivers::uart::ns16550")
    module_path: &'static str,
    /// Rust type name (e.g., "Ns16550")
    type_name: &'static str,
    /// Rust config type name (e.g., "Ns16550Config")
    config_type: &'static str,
    /// Which service traits this driver implements (used for validation)
    #[allow(dead_code)] // used by validation logic, read via RON device.services match
    services: &'static [&'static str],
}

/// Registry of known drivers.
const KNOWN_DRIVERS: &[DriverInfo] = &[
    DriverInfo {
        name: "ns16550",
        module_path: "fstart_drivers::uart::ns16550",
        type_name: "Ns16550",
        config_type: "Ns16550Config",
        services: &["Console"],
    },
    DriverInfo {
        name: "pl011",
        module_path: "fstart_drivers::uart::pl011",
        type_name: "Pl011",
        config_type: "Pl011Config",
        services: &["Console"],
    },
];

/// Look up driver info by RON driver name.
fn find_driver(name: &str) -> Option<&'static DriverInfo> {
    KNOWN_DRIVERS.iter().find(|d| d.name == name)
}

/// Generate the complete Rust source for a stage's main.rs.
///
/// This is the heart of fstart's "RON drives everything" philosophy.
/// The returned string is valid Rust source to be `include!()`d in the
/// `#![no_std] #![no_main]` crate root.
pub fn generate_stage_source(config: &BoardConfig, stage_name: Option<&str>) -> String {
    let mut out = String::new();

    // File header
    out.push_str("// AUTO-GENERATED by fstart-codegen from board.ron\n");
    out.push_str("// DO NOT EDIT — changes will be overwritten.\n\n");

    // Pull in platform entry point (_start -> fstart_main) and runtime (panic handler).
    let platform = config.platform.as_str();
    match platform {
        "riscv64" => {
            out.push_str("extern crate fstart_platform_riscv64;\n");
        }
        "aarch64" => {
            out.push_str("extern crate fstart_platform_aarch64;\n");
        }
        p => {
            out.push_str(&format!("compile_error!(\"unsupported platform: {p}\");\n"));
        }
    }
    out.push_str("extern crate fstart_runtime;\n\n");

    // Get capabilities for this stage
    let capabilities = match (&config.stages, stage_name) {
        (StageLayout::Monolithic(mono), _) => &mono.capabilities,
        (StageLayout::MultiStage(stages), Some(name)) => {
            if let Some(stage) = stages.iter().find(|s| s.name.as_str() == name) {
                &stage.capabilities
            } else {
                return format!("compile_error!(\"stage '{name}' not found in board config\");\n");
            }
        }
        (StageLayout::MultiStage(_), None) => {
            return "compile_error!(\"multi-stage board requires FSTART_STAGE_NAME\");\n"
                .to_string();
        }
    };

    // Validate capability ordering before generating code.
    if let Some(err) = validate_capability_ordering(capabilities) {
        return format!("compile_error!(\"{err}\");\n");
    }

    // Collect all devices referenced by capabilities to determine what we need.
    // For now, generate structs for ALL declared devices.
    generate_imports(&mut out, &config.devices);
    generate_devices_struct(&mut out, &config.devices);
    generate_stage_context(&mut out, &config.devices);
    generate_fstart_main(&mut out, config, capabilities, platform);

    out
}

/// Validate that capabilities are in a legal order.
///
/// Rules:
/// - Any capability that logs (all of them except ConsoleInit itself) must
///   come after at least one ConsoleInit.
/// - DriverInit must come after ConsoleInit (it logs device init results).
/// - StageLoad / PayloadLoad should be the last capability (nothing runs after
///   a jump). We warn but don't hard-error since the board author may know
///   what they're doing.
fn validate_capability_ordering(capabilities: &[Capability]) -> Option<String> {
    let mut console_inited = false;

    for cap in capabilities {
        match cap {
            Capability::ConsoleInit { .. } => {
                console_inited = true;
            }
            Capability::MemoryInit if !console_inited => {
                return Some(
                    "MemoryInit capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            Capability::DriverInit if !console_inited => {
                return Some(
                    "DriverInit capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            Capability::SigVerify if !console_inited => {
                return Some(
                    "SigVerify capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            Capability::FdtPrepare if !console_inited => {
                return Some(
                    "FdtPrepare capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            Capability::PayloadLoad if !console_inited => {
                return Some(
                    "PayloadLoad capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            Capability::StageLoad { .. } if !console_inited => {
                return Some(
                    "StageLoad capability requires ConsoleInit to appear earlier \
                     in the capability list (needed for logging)"
                        .to_string(),
                );
            }
            _ => {}
        }
    }

    None
}

/// Emit `use` statements for all driver types needed by this board's devices.
fn generate_imports(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("use fstart_services::Console;\n");
    out.push_str("use fstart_services::device::Device;\n\n");

    // Collect unique driver modules
    let mut seen: Vec<&str> = Vec::new();
    for dev in devices {
        let drv_name = dev.driver.as_str();
        if !seen.contains(&drv_name) {
            if let Some(info) = find_driver(drv_name) {
                out.push_str(&format!(
                    "use {}::{{{}, {}}};\n",
                    info.module_path, info.type_name, info.config_type,
                ));
            }
            seen.push(drv_name);
        }
    }
    out.push('\n');
}

/// Emit the `Devices` struct — one concrete typed field per device.
fn generate_devices_struct(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("/// All devices for this board, with concrete types.\n");
    out.push_str("struct Devices {\n");
    for dev in devices {
        let field_name = dev.name.as_str();
        if let Some(info) = find_driver(dev.driver.as_str()) {
            out.push_str(&format!("    {field_name}: {},\n", info.type_name));
        } else {
            out.push_str(&format!("    // unknown driver: {}\n", dev.driver.as_str()));
        }
    }
    out.push_str("}\n\n");
}

/// Emit the `StageContext` struct with typed service accessors.
fn generate_stage_context(out: &mut String, devices: &[DeviceConfig]) {
    out.push_str("/// Stage context — provides typed access to services.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("struct StageContext {\n");
    out.push_str("    devices: Devices,\n");
    out.push_str("}\n\n");

    out.push_str("#[allow(dead_code)]\n");
    out.push_str("impl StageContext {\n");

    // Find the first device providing each service type and generate an accessor.
    let service_types = ["Console", "BlockDevice", "Timer"];
    let accessor_names = ["console", "block_device", "timer"];
    let trait_names = ["Console", "BlockDevice", "Timer"];

    for (i, svc) in service_types.iter().enumerate() {
        if let Some(dev) = devices
            .iter()
            .find(|d| d.services.iter().any(|s| s.as_str() == *svc))
        {
            let field = dev.name.as_str();
            let accessor = accessor_names[i];
            let trait_name = trait_names[i];
            out.push_str("    #[inline]\n");
            out.push_str(&format!(
                "    fn {accessor}(&self) -> &(impl {trait_name} + '_) {{\n"
            ));
            out.push_str(&format!("        &self.devices.{field}\n"));
            out.push_str("    }\n\n");
        }
    }

    out.push_str("}\n\n");
}

/// Emit the `fstart_main()` function — device construction, capability
/// execution, and halt.
fn generate_fstart_main(
    out: &mut String,
    config: &BoardConfig,
    capabilities: &[Capability],
    platform: &str,
) {
    let halt_fn = match platform {
        "riscv64" => "fstart_platform_riscv64::halt()",
        "aarch64" => "fstart_platform_aarch64::halt()",
        _ => "loop { core::hint::spin_loop(); }",
    };

    out.push_str("#[no_mangle]\n");
    out.push_str("pub extern \"Rust\" fn fstart_main() -> ! {\n");

    // --- Phase 1: Construct all devices (bind phase) ---
    out.push_str("    // === Device construction (bind phase) ===\n");
    for dev in &config.devices {
        generate_device_construction(out, dev, halt_fn);
    }
    out.push('\n');

    // Track which devices have been initialised by capabilities so DriverInit
    // can skip them and avoid double-init.
    let mut inited_devices: Vec<String> = Vec::new();

    // Track the first console device name for passing to later capabilities.
    let mut console_device: Option<String> = None;

    // --- Phase 2: Execute capabilities in declared order ---
    out.push_str("    // === Capability execution ===\n");
    for cap in capabilities {
        match cap {
            Capability::ConsoleInit { device } => {
                let dev_name = device.as_str();
                generate_console_init(out, dev_name, &config.devices, halt_fn);
                inited_devices.push(dev_name.to_string());
                if console_device.is_none() {
                    console_device = Some(dev_name.to_string());
                }
            }
            Capability::MemoryInit => {
                generate_memory_init(out, &console_device);
            }
            Capability::DriverInit => {
                generate_driver_init(
                    out,
                    &config.devices,
                    &inited_devices,
                    halt_fn,
                    &console_device,
                );
                // After DriverInit, all devices are initialised.
                for dev in &config.devices {
                    let name = dev.name.as_str().to_string();
                    if !inited_devices.contains(&name) {
                        inited_devices.push(name);
                    }
                }
            }
            Capability::SigVerify => {
                generate_sig_verify(out, &console_device);
            }
            Capability::FdtPrepare => {
                generate_fdt_prepare(out, &console_device);
            }
            Capability::PayloadLoad => {
                generate_payload_load(out, &console_device);
            }
            Capability::StageLoad { next_stage } => {
                generate_stage_load(out, next_stage.as_str(), &console_device);
            }
        }
    }

    // --- Phase 3: Build context and finalize ---
    out.push_str("\n    // === Build stage context ===\n");
    let ctx_binding = if console_device.is_some() {
        "ctx"
    } else {
        "_ctx"
    };
    out.push_str(&format!("    let {ctx_binding} = StageContext {{\n"));
    out.push_str("        devices: Devices {\n");
    for dev in &config.devices {
        if find_driver(dev.driver.as_str()).is_some() {
            out.push_str(&format!("            {0}: {0},\n", dev.name.as_str()));
        }
    }
    out.push_str("        },\n");
    out.push_str("    };\n\n");

    // Log completion via the context's console accessor (devices have been
    // moved into the Devices struct, so we use ctx instead of bare variables).
    if console_device.is_some() {
        out.push_str(
            "    let _ = ctx.console().write_line(\"[fstart] all capabilities complete\");\n",
        );
    }

    // Halt
    out.push_str("    // Stage complete — halt\n");
    out.push_str(&format!("    {halt_fn};\n"));

    out.push_str("}\n");
}

/// Generate a device construction call using the `Device` trait.
fn generate_device_construction(out: &mut String, dev: &DeviceConfig, halt_fn: &str) {
    let name = dev.name.as_str();
    let drv_name = dev.driver.as_str();

    let Some(info) = find_driver(drv_name) else {
        out.push_str(&format!(
            "    compile_error!(\"unknown driver: {drv_name}\");\n"
        ));
        return;
    };

    out.push_str(&format!(
        "    let {name} = {}::new(&{} {{\n",
        info.type_name, info.config_type
    ));

    // Map Resources fields to config fields based on driver type.
    generate_config_fields(out, dev, info);

    out.push_str(&format!("    }}).unwrap_or_else(|_| {halt_fn});\n"));
}

/// Map RON Resources to driver-specific Config fields.
fn generate_config_fields(out: &mut String, dev: &DeviceConfig, info: &DriverInfo) {
    let res = &dev.resources;
    let name = dev.name.as_str();

    match info.name {
        "ns16550" | "pl011" => {
            // UART drivers need: base_addr, clock_freq, baud_rate
            if let Some(base) = res.mmio_base {
                out.push_str(&format!("        base_addr: {base:#x},\n"));
            } else {
                out.push_str(&format!(
                    "        base_addr: compile_error!(\"device '{name}' requires mmio_base\"),\n"
                ));
            }
            out.push_str(&format!(
                "        clock_freq: {},\n",
                res.clock_freq.unwrap_or(0)
            ));
            out.push_str(&format!(
                "        baud_rate: {},\n",
                res.baud_rate.unwrap_or(115200)
            ));
        }
        _ => {
            out.push_str(&format!(
                "        // TODO: config mapping for driver '{}'",
                info.name
            ));
        }
    }
}

/// Generate code for the ConsoleInit capability.
fn generate_console_init(
    out: &mut String,
    device_name: &str,
    devices: &[DeviceConfig],
    halt_fn: &str,
) {
    let Some(dev) = devices.iter().find(|d| d.name.as_str() == device_name) else {
        out.push_str(&format!(
            "    compile_error!(\"ConsoleInit references device '{device_name}' which is not declared\");\n"
        ));
        return;
    };

    let drv_name = dev.driver.as_str();
    let Some(_info) = find_driver(drv_name) else {
        out.push_str(&format!(
            "    compile_error!(\"device '{device_name}' uses unknown driver '{drv_name}'\");\n"
        ));
        return;
    };

    // Check that this device actually provides Console service
    if !dev.services.iter().any(|s| s.as_str() == "Console") {
        out.push_str(&format!(
            "    compile_error!(\"ConsoleInit requires Console service but device '{device_name}' does not provide it\");\n"
        ));
        return;
    }

    out.push_str(&format!("    // ConsoleInit: {drv_name}\n"));
    out.push_str(&format!(
        "    {device_name}.init().unwrap_or_else(|_| {halt_fn});\n"
    ));
    out.push_str(&format!(
        "    fstart_capabilities::console_ready(&{device_name}, \"{device_name}\", \"{drv_name}\");\n"
    ));
}

/// Generate code for the MemoryInit capability.
fn generate_memory_init(out: &mut String, console_device: &Option<String>) {
    out.push_str("    // MemoryInit\n");
    if let Some(ref con) = console_device {
        out.push_str(&format!("    fstart_capabilities::memory_init(&{con});\n"));
    }
}

/// Generate code for the DriverInit capability.
///
/// Initialises all devices that were not already initialised by earlier
/// capabilities (e.g., ConsoleInit already called init() on the UART).
fn generate_driver_init(
    out: &mut String,
    devices: &[DeviceConfig],
    already_inited: &[String],
    halt_fn: &str,
    console_device: &Option<String>,
) {
    out.push_str("    // DriverInit: init remaining devices\n");

    let mut count = 0usize;
    for dev in devices {
        let name = dev.name.as_str();
        if already_inited.iter().any(|s| s == name) {
            out.push_str(&format!("    // {name}: already initialised\n"));
            continue;
        }
        if find_driver(dev.driver.as_str()).is_none() {
            continue; // unknown driver, already compile_error'd in construction
        }
        out.push_str(&format!(
            "    {name}.init().unwrap_or_else(|_| {halt_fn});\n"
        ));
        count += 1;
    }

    if let Some(ref con) = console_device {
        out.push_str(&format!(
            "    fstart_capabilities::driver_init_complete(&{con}, {count});\n"
        ));
    }
}

/// Generate code for the SigVerify capability.
fn generate_sig_verify(out: &mut String, console_device: &Option<String>) {
    out.push_str("    // SigVerify\n");
    if let Some(ref con) = console_device {
        out.push_str(&format!("    fstart_capabilities::sig_verify(&{con});\n"));
    }
}

/// Generate code for the FdtPrepare capability.
fn generate_fdt_prepare(out: &mut String, console_device: &Option<String>) {
    out.push_str("    // FdtPrepare\n");
    if let Some(ref con) = console_device {
        out.push_str(&format!("    fstart_capabilities::fdt_prepare(&{con});\n"));
    }
}

/// Generate code for the PayloadLoad capability.
fn generate_payload_load(out: &mut String, console_device: &Option<String>) {
    out.push_str("    // PayloadLoad\n");
    if let Some(ref con) = console_device {
        out.push_str(&format!("    fstart_capabilities::payload_load(&{con});\n"));
    }
}

/// Generate code for the StageLoad capability.
fn generate_stage_load(out: &mut String, next_stage: &str, console_device: &Option<String>) {
    out.push_str(&format!("    // StageLoad -> {next_stage}\n"));
    if let Some(ref con) = console_device {
        out.push_str(&format!(
            "    fstart_capabilities::stage_load(&{con}, \"{next_stage}\");\n"
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a minimal board config for testing.
    fn test_board_config(capabilities: heapless::Vec<Capability, 16>) -> BoardConfig {
        use fstart_types::*;
        use heapless::String as HString;

        let mut devices = heapless::Vec::new();
        let _ = devices.push(DeviceConfig {
            name: HString::try_from("uart0").unwrap(),
            compatible: HString::try_from("ns16550a").unwrap(),
            driver: HString::try_from("ns16550").unwrap(),
            services: {
                let mut v = heapless::Vec::new();
                let _ = v.push(HString::try_from("Console").unwrap());
                v
            },
            resources: Resources {
                mmio_base: Some(0x1000_0000),
                clock_freq: Some(3_686_400),
                baud_rate: Some(115_200),
                irq: Some(10),
                ..Default::default()
            },
            parent: None,
        });

        BoardConfig {
            name: HString::try_from("test-board").unwrap(),
            platform: HString::try_from("riscv64").unwrap(),
            memory: MemoryMap {
                regions: {
                    let mut v = heapless::Vec::new();
                    let _ = v.push(MemoryRegion {
                        name: HString::try_from("ram").unwrap(),
                        base: 0x8000_0000,
                        size: 0x0800_0000,
                        kind: RegionKind::Ram,
                    });
                    v
                },
            },
            devices,
            stages: StageLayout::Monolithic(MonolithicConfig {
                capabilities,
                load_addr: 0x8000_0000,
                stack_size: 0x10000,
            }),
            security: SecurityConfig {
                signing_algorithm: SignatureAlgorithm::Ed25519,
                pubkey_file: HString::try_from("keys/dev.pub").unwrap(),
                required_digests: {
                    let mut v = heapless::Vec::new();
                    let _ = v.push(DigestAlgorithm::Sha256);
                    v
                },
            },
            mode: BuildMode::Rigid,
            payload: None,
        }
    }

    #[test]
    fn test_console_init_generates_device_init_and_banner() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(source.contains("uart0.init()"), "should call init()");
        assert!(
            source.contains("fstart_capabilities::console_ready"),
            "should call console_ready"
        );
        assert!(source.contains("Ns16550::new"), "should construct Ns16550");
        assert!(
            source.contains("struct Devices"),
            "should define Devices struct"
        );
        assert!(
            source.contains("struct StageContext"),
            "should define StageContext"
        );
    }

    #[test]
    fn test_memory_init_after_console() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let _ = caps.push(Capability::MemoryInit);
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("fstart_capabilities::memory_init(&uart0)"),
            "should call memory_init with console ref"
        );
    }

    #[test]
    fn test_memory_init_without_console_is_error() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::MemoryInit);
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("compile_error!"),
            "should emit compile_error for MemoryInit without ConsoleInit"
        );
    }

    #[test]
    fn test_driver_init_skips_already_inited() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let _ = caps.push(Capability::DriverInit);
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("uart0: already initialised"),
            "should skip uart0 since ConsoleInit already inited it"
        );
        assert!(
            source.contains("fstart_capabilities::driver_init_complete(&uart0, 0)"),
            "should report 0 additional devices inited"
        );
    }

    #[test]
    fn test_sig_verify_generates_call() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let _ = caps.push(Capability::SigVerify);
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("fstart_capabilities::sig_verify(&uart0)"),
            "should call sig_verify"
        );
    }

    #[test]
    fn test_stage_load_generates_call() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let _ = caps.push(Capability::StageLoad {
            next_stage: heapless::String::try_from("main").unwrap(),
        });
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("fstart_capabilities::stage_load(&uart0, \"main\")"),
            "should call stage_load with next_stage name"
        );
    }

    #[test]
    fn test_unknown_driver_is_compile_error() {
        use fstart_types::*;
        use heapless::String as HString;

        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: HString::try_from("uart0").unwrap(),
        });

        let mut config = test_board_config(caps);
        config.devices[0].driver = HString::try_from("nonexistent").unwrap();

        let source = generate_stage_source(&config, None);
        assert!(
            source.contains("compile_error!"),
            "should emit compile_error for unknown driver"
        );
    }

    #[test]
    fn test_all_capabilities_complete_message() {
        let mut caps = heapless::Vec::new();
        let _ = caps.push(Capability::ConsoleInit {
            device: heapless::String::try_from("uart0").unwrap(),
        });
        let config = test_board_config(caps);
        let source = generate_stage_source(&config, None);

        assert!(
            source.contains("[fstart] all capabilities complete"),
            "should log completion message"
        );
    }
}
