[package]
name = "fstart-board-licheerv-dock"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "licheerv-dock"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-board-meta = { workspace = true }
fstart-driver-ns16550 = { workspace = true }
fstart-driver-sunxi-d1-ccu = { workspace = true }
fstart-driver-sunxi-d1-dramc = { workspace = true }
fstart-driver-sunxi-mmc = { workspace = true }

serde_json = { workspace = true }

[[bin]]
name = "fstart-board-metadata"
path = "src/bin/fstart-board-metadata.rs"

