[package]
name = "fstart-board-licheerv-dock"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "licheerv-dock"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"
stage-package = "fstart-board-licheerv-dock-stage"
stage-bin = "fstart-stage"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
