[package]
name = "fstart-board-licheerv-dock"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "licheerv-dock"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"
stage-bin = "fstart-stage"
stage-recipe = "sunxi-mmc-linux"

[features]
default = []
stage = [
  "dep:fstart-stage",
  "dep:fstart-services",
  "dep:fstart-driver-ns16550",
  "dep:fstart-driver-sunxi-mmc",
  "dep:fstart-platform-riscv64",
  "fstart-stage/sunxi",
  "fstart-stage/ns16550",
  "dep:fstart-driver-sunxi-d1-ccu",
  "dep:fstart-driver-sunxi-d1-dramc",
]
ffs = ["stage", "fstart-stage/ffs"]

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-driver-ns16550 = { workspace = true, optional = true }
fstart-driver-sunxi-mmc = { workspace = true, optional = true }
fstart-platform-riscv64 = { workspace = true, optional = true }
fstart-driver-sunxi-d1-ccu = { workspace = true, optional = true }
fstart-driver-sunxi-d1-dramc = { workspace = true, optional = true }
