[package]
name = "fstart-board-qemu-armv7"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.fstart]
board = "qemu-armv7"
platform = "armv7"
target = "armv7a-none-eabi"
stage-bin = "fstart-stage"
features = ["qemu-armv7"]

[features]
default = []
host = ["dep:fbuild", "fstart-platform-qemu/host"]
runtime = []
stage = [
  "runtime",
  "dep:fstart-driver-uart",
  "dep:fstart-stage",
  "fstart-platform-qemu/stage",
]
armv7 = ["fstart-stage?/armv7", "fstart-platform-qemu/armv7"]
ffs = ["fstart-stage?/ffs"]
bootstrap = ["fstart-stage?/bootstrap"]
ffs-signature = ["fstart-stage?/ffs-signature"]
ed25519 = ["fstart-stage?/ed25519"]
sha2-digest = ["fstart-stage?/sha2-digest"]
sha3-digest = ["fstart-stage?/sha3-digest"]
lz4 = ["fstart-stage?/lz4"]
fdt = ["fstart-stage?/fdt"]
linux = ["fstart-stage?/linux", "fstart-platform-qemu/linux"]
fit = ["fstart-stage?/fit"]
handoff = ["fstart-stage?/handoff"]
qemu-armv7 = []

[dependencies]
fstart-core = { path = "../../../crates/core" }
fstart-platform-qemu = { path = "../../../crates/platform-qemu" }
fstart-driver-uart = { path = "../../../crates/driver-uart", optional = true }
fstart-stage = { path = "../../../crates/stage", optional = true }
fbuild = { path = "../../../tools/fbuild", optional = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
required-features = ["stage"]

[[bin]]
name = "fstart-host"
path = "src/host_main.rs"
required-features = ["host"]
