//! Composable capability modules for firmware stages.
//!
//! Each capability is a unit of firmware functionality. The board RON file
//! declares which capabilities run in which order. Codegen generates a
//! `fstart_main()` that calls them in sequence.
//!
//! Capability functions accept service trait references (e.g., `&dyn Console`)
//! rather than a monolithic context struct. The concrete `StageContext` and
//! `Devices` structs are generated by codegen, not defined here.
//!
//! ## FFS Capabilities
//!
//! When the `ffs` feature is enabled, `sig_verify`, `stage_load`, and
//! `payload_load` perform real FFS operations: scanning for the anchor,
//! verifying manifest signatures, reading file segments, and jumping to
//! loaded code. Without the `ffs` feature, stub variants are used.
//!
//! See [docs/driver-model.md](../../docs/driver-model.md) for the full
//! driver model architecture.

#![no_std]

use fstart_services::Console;

// ---------------------------------------------------------------------------
// ConsoleInit
// ---------------------------------------------------------------------------

/// Log the console-ready banner after a console device is initialised.
///
/// Called by generated code after `Device::init()` succeeds on a console device.
pub fn console_ready(console: &dyn Console, device_name: &str, driver_name: &str) {
    let _ = console.write_str("[fstart] ");
    let _ = console.write_str(device_name);
    let _ = console.write_str(": ");
    let _ = console.write_str(driver_name);
    let _ = console.write_line(" console ready");
}

// ---------------------------------------------------------------------------
// MemoryInit
// ---------------------------------------------------------------------------

/// Initialise DRAM (memory training / memory controller setup).
///
/// In a real board this would perform SPD reads, memory training, and
/// controller configuration. For QEMU virt machines, RAM is always available
/// so this is a no-op that logs its execution.
///
/// Future: Accept a platform-specific memory-init trait or configuration.
pub fn memory_init(console: &dyn Console) {
    let _ = console.write_line("[fstart] capability: MemoryInit");
    // QEMU virt: RAM is pre-initialised, nothing to do.
    // Real boards: SPD read → training → controller init would go here.
    let _ = console.write_line("[fstart] memory init complete (no-op on QEMU)");
}

// ---------------------------------------------------------------------------
// DriverInit
// ---------------------------------------------------------------------------

/// Enumerate and initialise all declared devices/drivers.
///
/// Codegen generates the actual `Device::init()` calls for each device
/// that was not already initialised by an earlier capability (e.g.,
/// ConsoleInit already inits the UART). This function logs the phase
/// boundary; the individual init calls are inlined by codegen.
///
/// `device_count` is the total number of devices that were initialised
/// in this phase (provided by codegen, which knows the count).
pub fn driver_init_complete(console: &dyn Console, device_count: usize) {
    let _ = console.write_str("[fstart] capability: DriverInit (");
    // Format the count manually since we don't have format! in no_std
    let _ = write_usize(console, device_count);
    let _ = console.write_line(" devices)");
}

// ---------------------------------------------------------------------------
// SigVerify
// ---------------------------------------------------------------------------

/// Verify the firmware filesystem manifest signature.
///
/// Scans the firmware image for the FFS anchor, reads the RO manifest,
/// verifies its cryptographic signature, and checks file digests.
///
/// `flash_base` and `flash_size` specify where the firmware image sits
/// in memory. If `flash_size` is 0, verification is skipped (no FFS
/// image available).
#[cfg(feature = "ffs")]
pub fn sig_verify(console: &dyn Console, flash_base: u64, flash_size: u64) {
    let _ = console.write_line("[fstart] capability: SigVerify");

    if flash_size == 0 {
        let _ = console.write_line("[fstart] sig verify: no flash image configured, skipping");
        return;
    }

    // SAFETY: we trust that flash_base..flash_base+flash_size is mapped and
    // readable memory (guaranteed by the board config and platform setup).
    let image =
        unsafe { core::slice::from_raw_parts(flash_base as *const u8, flash_size as usize) };

    let reader = fstart_ffs::FfsReader::new(image);

    // Scan for the anchor block
    let anchor_offset = match reader.scan_for_anchor() {
        Ok(offset) => {
            let _ = console.write_str("[fstart] sig verify: anchor found at offset ");
            let _ = write_hex(console, offset as u64);
            let _ = console.write_line("");
            offset
        }
        Err(_) => {
            let _ = console.write_line("[fstart] sig verify: no FFS anchor found, skipping");
            return;
        }
    };

    // Read the anchor
    let anchor = match reader.read_anchor(anchor_offset) {
        Ok(a) => a,
        Err(e) => {
            let _ = console.write_str("[fstart] sig verify: failed to read anchor: ");
            let _ = console.write_line(reader_error_str(e));
            return;
        }
    };

    // Verify the RO manifest signature
    match reader.read_ro_manifest(&anchor) {
        Ok(manifest) => {
            let _ = console.write_str("[fstart] sig verify: RO manifest verified (");
            let _ = write_usize(console, manifest.entries.len());
            let _ = console.write_line(" files)");

            // Verify file digests for single-segment uncompressed files
            let mut verified = 0usize;
            let mut skipped = 0usize;
            for entry in &manifest.entries {
                match reader.verify_file_digests_raw(entry, anchor.ro_region_base) {
                    Ok(()) => verified += 1,
                    Err(fstart_ffs::ReaderError::CannotVerifyInPlace) => skipped += 1,
                    Err(_) => {
                        let _ = console.write_str("[fstart] sig verify: digest FAILED for: ");
                        let _ = console.write_line(entry.name.as_str());
                        return;
                    }
                }
            }
            let _ = console.write_str("[fstart] sig verify: ");
            let _ = write_usize(console, verified);
            let _ = console.write_str(" files verified, ");
            let _ = write_usize(console, skipped);
            let _ = console.write_line(" skipped (multi-segment)");
        }
        Err(e) => {
            let _ = console.write_str("[fstart] sig verify: manifest verification FAILED: ");
            let _ = console.write_line(reader_error_str(e));
        }
    }
}

/// Stub SigVerify when FFS feature is not enabled.
#[cfg(not(feature = "ffs"))]
pub fn sig_verify(console: &dyn Console, _flash_base: u64, _flash_size: u64) {
    let _ = console.write_line("[fstart] capability: SigVerify");
    let _ = console.write_line("[fstart] sig verify skipped (ffs feature not enabled)");
}

// ---------------------------------------------------------------------------
// FdtPrepare
// ---------------------------------------------------------------------------

/// Prepare a Flattened Device Tree for OS handoff.
///
/// Generates an FDT blob from the board RON configuration (or patches
/// a DTS-provided base FDT) and places it in memory where the payload
/// can find it.
///
/// Future: Accept memory map info and device list to populate FDT nodes.
pub fn fdt_prepare(console: &dyn Console) {
    let _ = console.write_line("[fstart] capability: FdtPrepare");
    // Skeleton: real implementation needs FDT generation from RON.
    let _ = console.write_line("[fstart] FDT prepare skipped (not yet implemented)");
}

// ---------------------------------------------------------------------------
// PayloadLoad
// ---------------------------------------------------------------------------

/// Load and jump to the payload (OS kernel, shell, etc.).
///
/// Reads the payload from FFS, copies its segments to load addresses,
/// and transfers control via the provided `jump_to` function.
#[cfg(feature = "ffs")]
pub fn payload_load(
    console: &dyn Console,
    flash_base: u64,
    flash_size: u64,
    jump_to: fn(u64) -> !,
) {
    let _ = console.write_line("[fstart] capability: PayloadLoad");

    if flash_size == 0 {
        let _ = console.write_line("[fstart] payload load: no flash image configured, skipping");
        return;
    }

    // SAFETY: flash_base..flash_base+flash_size is mapped readable memory.
    let image =
        unsafe { core::slice::from_raw_parts(flash_base as *const u8, flash_size as usize) };
    let reader = fstart_ffs::FfsReader::new(image);

    let anchor = match find_anchor_and_manifest(&reader, console) {
        Some((a, _m)) => a,
        None => return,
    };

    let manifest = match reader.read_ro_manifest(&anchor) {
        Ok(m) => m,
        Err(e) => {
            let _ = console.write_str("[fstart] payload load: manifest error: ");
            let _ = console.write_line(reader_error_str(e));
            return;
        }
    };

    // Look for a Payload file type
    let payload_file = manifest
        .entries
        .iter()
        .find(|e| e.file_type == fstart_types::ffs::FileType::Payload);

    let payload_file = match payload_file {
        Some(f) => f,
        None => {
            let _ = console.write_line("[fstart] payload load: no payload found in manifest");
            return;
        }
    };

    let _ = console.write_str("[fstart] payload load: loading '");
    let _ = console.write_str(payload_file.name.as_str());
    let _ = console.write_line("'");

    // Load segments
    let entry_addr = match load_file_segments(&reader, payload_file, anchor.ro_region_base, console)
    {
        Some(addr) => addr,
        None => return,
    };

    let _ = console.write_str("[fstart] payload load: jumping to ");
    let _ = write_hex(console, entry_addr);
    let _ = console.write_line("");

    jump_to(entry_addr);
}

/// Stub PayloadLoad when FFS feature is not enabled.
#[cfg(not(feature = "ffs"))]
pub fn payload_load_stub(console: &dyn Console) {
    let _ = console.write_line("[fstart] capability: PayloadLoad");
    let _ = console.write_line("[fstart] payload load skipped (ffs feature not enabled)");
}

/// Stub PayloadLoad without FFS — called when flash_base is not configured.
pub fn payload_load_stub_no_flash(console: &dyn Console) {
    let _ = console.write_line("[fstart] capability: PayloadLoad");
    let _ = console.write_line("[fstart] payload load skipped (not yet implemented)");
}

// ---------------------------------------------------------------------------
// StageLoad
// ---------------------------------------------------------------------------

/// Load the next stage from FFS into RAM and jump to it.
///
/// Reads the named stage binary from the firmware filesystem, copies its
/// segments to the load addresses, and transfers control via `jump_to`.
#[cfg(feature = "ffs")]
pub fn stage_load(
    console: &dyn Console,
    next_stage: &str,
    flash_base: u64,
    flash_size: u64,
    jump_to: fn(u64) -> !,
) {
    let _ = console.write_str("[fstart] capability: StageLoad -> ");
    let _ = console.write_line(next_stage);

    if flash_size == 0 {
        let _ = console.write_line("[fstart] stage load: no flash image configured, skipping");
        return;
    }

    // SAFETY: flash_base..flash_base+flash_size is mapped readable memory.
    let image =
        unsafe { core::slice::from_raw_parts(flash_base as *const u8, flash_size as usize) };
    let reader = fstart_ffs::FfsReader::new(image);

    let anchor = match find_anchor_and_manifest(&reader, console) {
        Some((a, _m)) => a,
        None => return,
    };

    let manifest = match reader.read_ro_manifest(&anchor) {
        Ok(m) => m,
        Err(e) => {
            let _ = console.write_str("[fstart] stage load: manifest error: ");
            let _ = console.write_line(reader_error_str(e));
            return;
        }
    };

    // Look up the stage by name in the manifest
    let stage_file = match fstart_ffs::FfsReader::find_file(&manifest, next_stage) {
        Ok(f) => f,
        Err(_) => {
            let _ = console.write_str("[fstart] stage load: stage '");
            let _ = console.write_str(next_stage);
            let _ = console.write_line("' not found in manifest");
            return;
        }
    };

    let _ = console.write_str("[fstart] stage load: loading '");
    let _ = console.write_str(next_stage);
    let _ = console.write_str("' (");
    let _ = write_usize(console, stage_file.segments.len());
    let _ = console.write_line(" segments)");

    // Load all segments to their load addresses
    let entry_addr = match load_file_segments(&reader, stage_file, anchor.ro_region_base, console) {
        Some(addr) => addr,
        None => return,
    };

    let _ = console.write_str("[fstart] stage load: jumping to ");
    let _ = write_hex(console, entry_addr);
    let _ = console.write_line("");

    jump_to(entry_addr);
}

/// Stub StageLoad — called when flash_base is not configured.
pub fn stage_load_stub(console: &dyn Console, next_stage: &str) {
    let _ = console.write_str("[fstart] capability: StageLoad -> ");
    let _ = console.write_line(next_stage);
    let _ = console.write_line("[fstart] stage load skipped (not yet wired to FFS)");
}

// ---------------------------------------------------------------------------
// FFS Helpers (behind `ffs` feature)
// ---------------------------------------------------------------------------

/// Scan for the FFS anchor and read the RO manifest.
///
/// Returns (AnchorBlock, Manifest) on success, or None on failure (with
/// error logged to console).
#[cfg(feature = "ffs")]
fn find_anchor_and_manifest<'a>(
    reader: &fstart_ffs::FfsReader<'a>,
    console: &dyn Console,
) -> Option<(fstart_types::ffs::AnchorBlock, fstart_types::ffs::Manifest)> {
    let anchor_offset = match reader.scan_for_anchor() {
        Ok(offset) => offset,
        Err(_) => {
            let _ = console.write_line("[fstart] FFS: no anchor found in flash image");
            return None;
        }
    };

    let anchor = match reader.read_anchor(anchor_offset) {
        Ok(a) => a,
        Err(e) => {
            let _ = console.write_str("[fstart] FFS: failed to read anchor: ");
            let _ = console.write_line(reader_error_str(e));
            return None;
        }
    };

    let manifest = match reader.read_ro_manifest(&anchor) {
        Ok(m) => m,
        Err(e) => {
            let _ = console.write_str("[fstart] FFS: manifest verification failed: ");
            let _ = console.write_line(reader_error_str(e));
            return None;
        }
    };

    Some((anchor, manifest))
}

/// Load all segments of a file to their load addresses.
///
/// Returns the entry address (load_addr of the first Code segment, or
/// load_addr of the first segment if no Code segments).
#[cfg(feature = "ffs")]
fn load_file_segments(
    reader: &fstart_ffs::FfsReader<'_>,
    file: &fstart_types::ffs::FileEntry,
    region_base: u32,
    console: &dyn Console,
) -> Option<u64> {
    let mut entry_addr: Option<u64> = None;

    for seg in &file.segments {
        if seg.kind == fstart_types::ffs::SegmentKind::Bss {
            // BSS: zero-fill at load_addr
            let dest = seg.load_addr as *mut u8;
            // SAFETY: we trust the board config; the load_addr points to writable RAM.
            unsafe {
                core::ptr::write_bytes(dest, 0, seg.loaded_size as usize);
            }
            let _ = console.write_str("[fstart]   BSS: ");
            let _ = write_hex(console, seg.load_addr);
            let _ = console.write_str(" (");
            let _ = write_usize(console, seg.loaded_size as usize);
            let _ = console.write_line(" bytes zeroed)");
        } else {
            // Data segment: copy from flash to load_addr
            let data = match reader.read_segment_data(seg, region_base) {
                Ok(d) => d,
                Err(e) => {
                    let _ = console.write_str("[fstart]   segment read error: ");
                    let _ = console.write_line(reader_error_str(e));
                    return None;
                }
            };

            if seg.compression != fstart_types::ffs::Compression::None {
                let _ = console.write_line("[fstart]   compressed segments not yet supported");
                return None;
            }

            let dest = seg.load_addr as *mut u8;
            // SAFETY: we trust the board config; the load_addr points to writable RAM
            // and `data.len()` bytes fit. The source and destination must not overlap
            // (flash → RAM is always non-overlapping).
            unsafe {
                core::ptr::copy_nonoverlapping(data.as_ptr(), dest, data.len());
            }
            let _ = console.write_str("[fstart]   ");
            let _ = console.write_str(seg.name.as_str());
            let _ = console.write_str(": ");
            let _ = write_hex(console, seg.load_addr);
            let _ = console.write_str(" (");
            let _ = write_usize(console, data.len());
            let _ = console.write_line(" bytes)");
        }

        // Use the first Code segment's load_addr as the entry point,
        // or fall back to the first segment's load_addr.
        if entry_addr.is_none() || seg.kind == fstart_types::ffs::SegmentKind::Code {
            entry_addr = Some(seg.load_addr);
        }
    }

    entry_addr
}

/// Map a ReaderError to a static string for logging.
#[cfg(feature = "ffs")]
fn reader_error_str(err: fstart_ffs::ReaderError) -> &'static str {
    match err {
        fstart_ffs::ReaderError::OutOfBounds => "out of bounds",
        fstart_ffs::ReaderError::BadMagic => "bad magic",
        fstart_ffs::ReaderError::UnsupportedVersion => "unsupported version",
        fstart_ffs::ReaderError::DeserializeError => "deserialize error",
        fstart_ffs::ReaderError::SignatureInvalid => "signature invalid",
        fstart_ffs::ReaderError::KeyNotFound => "key not found",
        fstart_ffs::ReaderError::FileNotFound => "file not found",
        fstart_ffs::ReaderError::DigestMismatch => "digest mismatch",
        fstart_ffs::ReaderError::RwSlotNotFound => "RW slot not found",
        fstart_ffs::ReaderError::UnsupportedAlgorithm => "unsupported algorithm",
        fstart_ffs::ReaderError::CannotVerifyInPlace => "cannot verify in place",
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Write a `usize` as decimal to the console (no format! in no_std).
fn write_usize(console: &dyn Console, mut n: usize) -> Result<(), fstart_services::ServiceError> {
    if n == 0 {
        return console.write_byte(b'0');
    }
    // Max digits for u64 is 20; usize ≤ u64.
    let mut buf = [0u8; 20];
    let mut i = buf.len();
    while n > 0 {
        i -= 1;
        buf[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }
    console.write_bytes(&buf[i..])
}

/// Write a `u64` as hexadecimal (0x...) to the console.
#[cfg_attr(not(feature = "ffs"), allow(dead_code))]
fn write_hex(console: &dyn Console, mut n: u64) -> Result<(), fstart_services::ServiceError> {
    let _ = console.write_str("0x");
    if n == 0 {
        return console.write_byte(b'0');
    }
    let hex_chars = b"0123456789abcdef";
    let mut buf = [0u8; 16];
    let mut i = buf.len();
    while n > 0 {
        i -= 1;
        buf[i] = hex_chars[(n & 0xf) as usize];
        n >>= 4;
    }
    console.write_bytes(&buf[i..])
}
