//! Composable capability modules for firmware stages.
//!
//! Each capability is a unit of firmware functionality. The board RON file
//! declares which capabilities run in which order. Codegen generates a
//! `fstart_main()` that calls them in sequence.
//!
//! Capability functions accept service trait references (e.g., `&dyn Console`)
//! rather than a monolithic context struct. The concrete `StageContext` and
//! `Devices` structs are generated by codegen, not defined here.
//!
//! See [docs/driver-model.md](../../docs/driver-model.md) for the full
//! driver model architecture.

#![no_std]

use fstart_services::Console;

/// Log the console-ready banner after a console device is initialised.
///
/// Called by generated code after `Device::init()` succeeds on a console device.
pub fn console_ready(console: &dyn Console, device_name: &str, driver_name: &str) {
    let _ = console.write_str("[fstart] ");
    let _ = console.write_str(device_name);
    let _ = console.write_str(": ");
    let _ = console.write_str(driver_name);
    let _ = console.write_line(" console ready");
}
