[package]
name = "fstart-board-intel-d945gclf"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.fstart]
schema = 1
board = "intel-d945gclf"
platform = "x86_64"
target = "x86_64-unknown-none"
stage-bin = "fstart-stage"
build-profile = { dependency = "fstart-platform-intel", name = "rust" }

[package.metadata.fstart.variants.intel-d945gclf-postcar-debug]
features = ["x86-postcar-uart-debug"]

[features]
default = []
x86-postcar-uart-debug = ["fstart-arch/x86-postcar-uart-debug"]

[dependencies]
fstart-core = { path = "../../../crates/core", features = ["pci"] }
fstart-platform-intel = { path = "../../../crates/platform-intel" }
fstart-acpi = { path = "../../../crates/acpi", features = ["x86"] }
fstart-acpi-macros = { path = "../../../crates/acpi-macros" }
fstart-arch = { path = "../../../crates/arch", features = ["x86_64"] }
fstart-driver-intel = { path = "../../../crates/driver-intel", features = ["ffs-vbt"] }
fstart-driver-superio = { path = "../../../crates/driver-superio", features = ["acpi"] }
fstart-driver-uart = { path = "../../../crates/driver-uart", features = ["pio"] }
fstart-log = { path = "../../../crates/log" }
ufmt = { workspace = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
