[package]
name = "fstart-board-intel-d945gclf"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.fstart]
board = "intel-d945gclf"
platform = "x86_64"
target = "x86_64-unknown-none"
stage-bin = "fstart-stage"
features = [
  "intel-i945",
  "intel-ich7",
  "smsc-lpc47m15x",
]

[package.metadata.fstart.variants.intel-d945gclf-postcar-debug]
features = ["x86-postcar-uart-debug"]

[features]
default = []
host = ["dep:fbuild", "fstart-platform-intel/host"]
runtime = []
crabefi = ["fstart-stage?/crabefi"]
stage = [
  "runtime",
  "dep:fstart-driver-uart",
  "dep:fstart-stage",
  "fstart-platform-intel/stage",
]
x86_64 = ["fstart-stage?/x86_64"]
x86-static-page-tables = ["fstart-stage?/x86-static-page-tables"]
x86-writable-page-tables = ["fstart-stage?/x86-writable-page-tables"]
x86-1g-pages = ["fstart-stage?/x86-1g-pages"]
x86-postcar-uart-debug = ["fstart-arch/x86-postcar-uart-debug"]
ffs = ["fstart-stage?/ffs"]
bootstrap = ["fstart-stage?/bootstrap"]
ffs-signature = ["fstart-stage?/ffs-signature"]
ed25519 = ["fstart-stage?/ed25519"]
sha2-digest = ["fstart-stage?/sha2-digest"]
sha3-digest = ["fstart-stage?/sha3-digest"]
lz4 = ["fstart-stage?/lz4"]
fit = ["fstart-stage?/fit"]
fdt = ["fstart-stage?/fdt"]
handoff = ["fstart-stage?/handoff"]
intel-i945 = []
intel-ich7 = []
smsc-lpc47m15x = []
acpi = [
  "dep:fstart-acpi-macros",
  "fstart-stage?/acpi",
  "fstart-platform-intel/acpi",
  "fstart-driver-intel/acpi",
  "fstart-driver-intel/ffs-vbt",
  "fstart-driver-superio/acpi",
]
mp = ["stage", "fstart-platform-intel/mp"]
smbios = ["fstart-platform-intel/smbios"]
smm = [
  "dep:fstart-smm",
  "fstart-smm/stage-bin",
]

[dependencies]
fstart-core = { path = "../../../crates/core", features = ["pci"] }
fstart-platform-intel = { path = "../../../crates/platform-intel" }
fstart-acpi = { path = "../../../crates/acpi", features = ["x86"] }
fstart-acpi-macros = { path = "../../../crates/acpi-macros", optional = true }
fstart-arch = { path = "../../../crates/arch", features = ["x86_64"] }
fstart-driver-intel = { path = "../../../crates/driver-intel", features = ["ffs-vbt"] }
fstart-driver-superio = { path = "../../../crates/driver-superio" }
fstart-driver-uart = { path = "../../../crates/driver-uart", features = ["pio"], optional = true }
fstart-log = { path = "../../../crates/log" }
fstart-smm = { path = "../../../crates/smm", optional = true }
fstart-stage = { path = "../../../crates/stage", optional = true }
fbuild = { path = "../../../tools/fbuild", optional = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
required-features = ["stage"]

[[bin]]
name = "fstart-host"
path = "src/host_main.rs"
required-features = ["host"]
