[package]
name = "fstart-board-qemu-q35"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-q35"
platform = "x86_64"
target = "x86_64-unknown-none"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-board-meta = { workspace = true }
fstart-driver-ns16550 = { workspace = true }
fstart-driver-qemu-fw-cfg = { workspace = true }
fstart-driver-q35-hostbridge = { workspace = true }
fstart-driver-bochs-display = { workspace = true }

serde_json = { workspace = true }

[[bin]]
name = "fstart-board-metadata"
path = "src/bin/fstart-board-metadata.rs"

