[package]
name = "fstart-crabefi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fstart-core = { workspace = true }
crabefi = { git = "https://github.com/ArthurHeymans/CrabEFI.git", rev = "658ea1ef7e8f4195f5414ad1bb56b82fd22ff057", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
fstart-arch = { workspace = true, features = ["x86_64"] }

