[package]
name = "fstart-board-foxconn-d41s"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "foxconn-d41s"
platform = "x86_64"
target = "x86_64-unknown-none"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-platform-intel-pineview-ich7 = { workspace = true }
fstart-board-meta = { workspace = true }
fstart-driver-i2c-ck505 = { workspace = true }
fstart-driver-ite8721f = { workspace = true }
fstart-gpio-ich = { workspace = true }
fstart-hda = { workspace = true }
heapless = { workspace = true }
