[package]
name = "fstart-board-qemu-aarch64"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.fstart]
schema = 1
board = "qemu-aarch64"
platform = "aarch64"
stage-bin = "fstart-stage"
build-profile = { dependency = "fstart-platform-qemu", name = "aarch64-relocate" }

[features]
default = []
stage = ["dep:fstart-driver-uart", "dep:fstart-stage"]

[dependencies]
fstart-core = { path = "../../../crates/core" }
fstart-platform-qemu = { path = "../../../crates/platform-qemu", default-features = false }
fstart-driver-uart = { path = "../../../crates/driver-uart", optional = true }
fstart-stage = { path = "../../../crates/stage", default-features = false, optional = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
required-features = ["stage"]
