[package]
name = "fstart-driver-lenovo-pmh7"
description = "Lenovo PMH7 power-management hub driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fstart-arch-x86 = { workspace = true }
fstart-log = { workspace = true }
fstart-pio = { workspace = true }
fstart-services = { workspace = true }
serde = { workspace = true }
ufmt = { workspace = true }
