[package]
name = "fstart-board-lenovo-x61"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "lenovo-x61"
platform = "x86_64"
target = "x86_64-unknown-none"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-platform-intel-gm965-ich8 = { workspace = true }
fstart-board-meta = { workspace = true }
fstart-driver-i2c-ck505 = { workspace = true }
fstart-mainboard-lenovo-x61 = { workspace = true }
fstart-driver-nsc-pc87382 = { workspace = true }
fstart-driver-nsc-pc87392 = { workspace = true }
fstart-gpio-ich = { workspace = true }
fstart-hda = { workspace = true }
heapless = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "fstart-board-metadata"
path = "src/bin/fstart-board-metadata.rs"

