[package]
name = "fstart-board-lenovo-x61"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "lenovo-x61"
platform = "x86_64"
target = "x86_64-unknown-none"
stage-package = "fstart-board-lenovo-x61-stage"
stage-bin = "fstart-stage"

[dependencies]
fstart-types = { workspace = true }
fstart-board-meta = { workspace = true }
fstart-platform-intel-gm965-ich8 = { workspace = true }
fstart-mainboard-lenovo-x61 = { workspace = true }
