[package]
name = "fstart-intel-gma"
description = "Shared Intel GMA display initialization support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitflags = { workspace = true }
fstart-core = { workspace = true }
heapless = { workspace = true }
tock-registers = { workspace = true }
zerocopy = { workspace = true }
