[package]
name = "fstart-board-qemu-aarch64-uefi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-aarch64-uefi"
platform = "aarch64"
tool-bin = "fstart-board-tool"
target = "aarch64-unknown-none"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-board-meta = { workspace = true }
xtask = { path = "../../xtask" }
fstart-driver-pl011 = { workspace = true }
fstart-driver-pci-ecam = { workspace = true }
fstart-driver-bochs-display = { workspace = true }

[[bin]]
name = "fstart-board-tool"
path = "src/bin/fstart-board-tool.rs"
