[package]
name = "fstart-board-qemu-aarch64-uefi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-aarch64-uefi"
platform = "aarch64"
target = "aarch64-unknown-none"
stage-recipe = "board-stage-wrapper"
stage-bin = "fstart-stage"

[features]
default = []

stage = [
  "dep:fstart-stage",
  "dep:fstart-stage-runtime",
  "dep:fstart-services",
  "dep:fstart-log",
  "dep:fstart-platform-aarch64",
  "dep:fstart-driver-pl011",
  "dep:ufmt",
]
aarch64 = ["fstart-stage/aarch64"]
aarch64-el2-relocate-entry = ["fstart-stage/aarch64-el2-relocate-entry"]
pl011 = ["fstart-stage/pl011"]
pci-ecam = ["fstart-stage/pci-ecam"]
bochs-display = ["fstart-stage/bochs-display"]
ffs = ["fstart-stage/ffs"]
ed25519 = ["fstart-stage/ed25519"]
sha2-digest = ["fstart-stage/sha2-digest"]
sha3-digest = ["fstart-stage/sha3-digest"]
lz4 = ["fstart-stage/lz4"]
crabefi = ["fstart-stage/crabefi"]
flow-profile-minimal = ["fstart-stage/flow-profile-minimal"]
flow-profile-linuxboot = ["fstart-stage/flow-profile-linuxboot"]
flow-profile-uefi = ["fstart-stage/flow-profile-uefi"]
flow-profile-multistage = ["fstart-stage/flow-profile-multistage"]

stage-bootblock = []

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-stage-runtime = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-log = { workspace = true, optional = true }
fstart-platform-aarch64 = { workspace = true, optional = true }
fstart-driver-pl011 = { workspace = true, optional = true }
ufmt = { workspace = true, optional = true }
