[package]
name = "fstart-driver-pci-ecam"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fstart-board-meta = { workspace = true }
fstart-mmio = { workspace = true }
fstart-services = { workspace = true, features = ["pci"] }
fstart-log = { workspace = true }
heapless = { workspace = true }
ufmt = { workspace = true }
serde = { workspace = true }
