[package]
name = "fstart-board-qemu-sifive-u"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.fstart]
schema = 1
board = "qemu-sifive-u"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"
stage-bin = "fstart-stage"
features = ["qemu-sifive-u"]

[features]
default = []
host = ["dep:fbuild", "fstart-platform-qemu/host"]
runtime = []
stage = [
  "runtime",
  "dep:fstart-driver-uart",
  "dep:fstart-stage",
  "fstart-platform-qemu/stage",
]
riscv64 = ["fstart-stage?/riscv64", "fstart-platform-qemu/riscv64"]
ffs = ["fstart-stage?/ffs"]
bootstrap = ["fstart-stage?/bootstrap"]
ffs-signature = ["fstart-stage?/ffs-signature"]
ed25519 = ["fstart-stage?/ed25519"]
sha2-digest = ["fstart-stage?/sha2-digest"]
sha3-digest = ["fstart-stage?/sha3-digest"]
lz4 = ["fstart-stage?/lz4"]
fdt = ["fstart-stage?/fdt"]
linux = ["fstart-stage?/linux", "fstart-platform-qemu/linux"]
crabefi = ["fstart-stage?/crabefi", "fstart-platform-qemu/crabefi"]
qemu-sifive-u = []

[dependencies]
fstart-core = { path = "../../../crates/core" }
fstart-platform-qemu = { path = "../../../crates/platform-qemu" }
fstart-driver-uart = { path = "../../../crates/driver-uart", optional = true }
fstart-stage = { path = "../../../crates/stage", optional = true }
fbuild = { path = "../../../tools/fbuild", optional = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
required-features = ["stage"]

[[bin]]
name = "fstart-host"
path = "src/host_main.rs"
required-features = ["host"]
