[package]
name = "fstart-board-qemu-aarch64"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-aarch64"
platform = "aarch64"
target = "aarch64-unknown-none"
stage-package = "fstart-board-qemu-aarch64-stage"
stage-bin = "fstart-stage"

[dependencies]
fstart-board-qemu-aarch64-facts = { path = "facts" }
fstart-board-qemu-virt = { workspace = true }
fstart-types = { workspace = true, features = ["std"] }
