[package]
name = "fstart-board-qemu-aarch64"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-aarch64"
platform = "aarch64"
target = "aarch64-unknown-none"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-board-qemu-virt = { workspace = true }
fstart-device-registry = { workspace = true, features = ["all-drivers"] }
heapless = { workspace = true }
