//! SBSA entry point — flash-to-DRAM copy and early init.
//!
//! On SBSA-ref, TF-A BL31 jumps to the start of pflash1 (0x10000000) at EL2.
//! DRAM starts at 0x10000000000 (1 TiB), far beyond AArch64's +/- 4 GiB
//! ADRP relocation range. The firmware is linked for DRAM addresses, so we
//! need a position-independent stub in flash that:
//!
//! 1. Saves x0 (FDT pointer from TF-A)
//! 2. Calculates the binary size from linker symbols
//! 3. Copies the binary from flash to DRAM
//! 4. Jumps to the real `_start` in DRAM
//!
//! The DRAM `_start` then sets up the stack, clears BSS, and calls
//! `fstart_main` as usual.
//!
//! This is the same approach as coreboot's `bootblock_custom.S` for
//! qemu-sbsa.

use core::arch::global_asm;

global_asm!(
    r#"
    // =======================================================================
    // Flash stub: position-independent code at pflash1 base (0x10000000).
    // Copies firmware from flash to DRAM, then jumps to _start in DRAM.
    // =======================================================================
    .section .text.entry
    .global _start
_start:
    // Save x0 = FDT pointer from TF-A (passed via ARM_LINUX_KERNEL_AS_BL33)
    mov x20, x0

    // Disable all interrupts
    msr daifset, #0xf

    // Disable EL2 MMU + caches so we can access all of physical memory
    // (DRAM at 0x10000000000 may not be in TF-A's page tables).
    // This code runs from flash which is always identity-mapped by the
    // hardware, so disabling the MMU is safe here.
    mrs x0, sctlr_el2
    bic x0, x0, #0x1            // clear M bit (MMU enable)
    bic x0, x0, #0x4            // clear C bit (data cache)
    msr sctlr_el2, x0
    isb

    // Invalidate TLB and instruction cache for clean state
    tlbi alle2
    dsb sy
    isb
    ic iallu
    dsb sy
    isb

    // Determine where we are running from (flash base).
    // ADR is PC-relative and works regardless of link address.
    adr x0, _start              // x0 = current PC (flash address)

    // Load the link address of _start (DRAM address).
    // We use a literal pool since the address may be > 4 GiB.
    ldr x1, =_start             // x1 = linked address (DRAM)

    // If already running from DRAM (e.g., debugger loaded us there),
    // skip the copy.
    cmp x0, x1
    b.eq .Lskip_copy

    // Compute flash copy end address.
    // _binary_end - _start = size, but may not be 8-byte aligned.
    // We round up to the next 8-byte boundary and use an address
    // comparison instead of a byte counter (cbz on an unaligned
    // count would underflow past zero and copy forever).
    ldr x2, =_binary_end        // x2 = end of binary (DRAM link addr)
    sub x3, x2, x1              // x3 = size in bytes
    add x3, x3, #7              // round up to 8-byte boundary
    and x3, x3, #~7
    add x2, x0, x3              // x2 = flash source end address

    // Copy from flash (x0) to DRAM (x1), up to x2.
    // Both flash and DRAM are 8-byte aligned.
    mov x4, x1                  // x4 = DRAM destination (preserve x1)
.Lcopy_loop:
    cmp x0, x2
    b.hs .Lcopy_done
    ldr x5, [x0], #8
    str x5, [x4], #8
    b .Lcopy_loop
.Lcopy_done:

    // Data synchronization barrier — ensure all stores to DRAM are visible
    // before we jump there.
    dsb sy
    isb

    // Jump to _start in DRAM. x20 still holds the FDT pointer.
    // We use BR (absolute) since the DRAM address is far away.
    mov x0, x20                 // restore x0 = FDT pointer
    br x1                       // jump to _start in DRAM

.Lskip_copy:
    // Already in DRAM — fall through to normal startup.
    // Restore x0 = FDT pointer.
    mov x0, x20

    // === Normal DRAM entry point (same as entry.rs) ===

    // Save boot argument (FDT pointer) before any register is clobbered.
    mov x19, x0

    // Set up stack pointer
    ldr x0, =_stack_top
    mov sp, x0

    // Copy .data initializers from ROM to RAM.
    // For RAM-only layout, _data_load == _data_start so this is a no-op.
    ldr x0, =_data_load
    ldr x1, =_data_start
    ldr x2, =_data_end
1:
    cmp x1, x2
    b.ge 2f
    ldr x3, [x0], #8
    str x3, [x1], #8
    b 1b
2:
    // Clear BSS
    ldr x0, =_bss_start
    ldr x1, =_bss_end
3:
    cmp x0, x1
    b.ge 4f
    str xzr, [x0], #8
    b 3b
4:
    // Store boot DTB address to global (after BSS is cleared to zero)
    ldr x0, =BOOT_DTB_ADDR
    str x19, [x0]

    // Jump to Rust entry point.
    mov x0, #0
    bl fstart_main

    // Should never return
5:
    wfe
    b 5b
    "#
);

extern "Rust" {
    /// Rust entry point — generated by fstart-stage from board.ron capabilities.
    #[allow(dead_code)]
    fn fstart_main(handoff_ptr: usize) -> !;
}
