[package]
name = "fbuild"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
object = { workspace = true }
fstart-core = { workspace = true }
fstart-image-build = { workspace = true }
heapless = { workspace = true }
serde = { workspace = true }
toml = { version = "1.1", default-features = false, features = ["parse", "serde", "std"] }
