[package]
name = "fstart-board-qemu-q35-uefi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-q35-uefi"
platform = "x86_64"
target = "x86_64-unknown-none"
stage-recipe = "board-stage-wrapper"
stage-bin = "fstart-stage"

[features]
default = []

stage = [
  "dep:fstart-stage",
  "dep:fstart-stage-runtime",
  "dep:fstart-services",
  "dep:fstart-capabilities",
  "dep:fstart-log",
  "dep:fstart-platform-x86_64",
  "dep:fstart-driver-ns16550",
  "dep:fstart-driver-qemu-fw-cfg",
  "dep:fstart-driver-q35-hostbridge",
  "dep:ufmt",
]
x86_64 = ["fstart-stage/x86_64"]
ns16550 = ["fstart-stage/ns16550"]
ns16550-pio = ["fstart-stage/ns16550-pio"]
qemu-fw-cfg = ["fstart-stage/qemu-fw-cfg"]
q35-hostbridge = ["fstart-stage/q35-hostbridge"]
ffs = ["fstart-stage/ffs"]
ed25519 = ["fstart-stage/ed25519"]
sha2-digest = ["fstart-stage/sha2-digest"]
sha3-digest = ["fstart-stage/sha3-digest"]
lz4 = ["fstart-stage/lz4"]
handoff = ["fstart-stage/handoff"]
acpi = ["fstart-stage/acpi"]
acpi-load = ["fstart-stage/acpi-load"]
memory-detect = ["fstart-stage/memory-detect"]
crabefi = ["fstart-stage/crabefi"]
mp = ["fstart-stage/mp"]
cpu-generic-x86 = ["fstart-stage/cpu-generic-x86"]
x86-1g-pages = ["fstart-stage/x86-1g-pages"]
x86-boot = ["fstart-stage/x86-boot"]
x86-writable-page-tables = ["fstart-stage/x86-writable-page-tables"]
x86-static-page-tables = ["fstart-stage/x86-static-page-tables"]
flow-profile-minimal = ["fstart-stage/flow-profile-minimal"]
flow-profile-linuxboot = ["fstart-stage/flow-profile-linuxboot"]
flow-profile-uefi = ["fstart-stage/flow-profile-uefi"]
flow-profile-multistage = ["fstart-stage/flow-profile-multistage"]

stage-bootblock = []

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-stage-runtime = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-capabilities = { workspace = true, optional = true }
fstart-log = { workspace = true, optional = true }
fstart-platform-x86_64 = { workspace = true, optional = true }
fstart-driver-ns16550 = { workspace = true, features = ["pio"], optional = true }
fstart-driver-qemu-fw-cfg = { workspace = true, optional = true }
fstart-driver-q35-hostbridge = { workspace = true, optional = true }
ufmt = { workspace = true, optional = true }
