[package]
name = "fstart-smm-stage"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]
test = false

[dependencies]
fstart-driver-intel-ich7 = { workspace = true }
fstart-driver-intel-ich8 = { workspace = true }
fstart-driver-intel-ich9 = { workspace = true }
fstart-mainboard-lenovo-x61 = { workspace = true }
fstart-mainboard-lenovo-x200 = { workspace = true }
fstart-smm-runtime = { workspace = true }
