[package]
name = "fstart-board-qemu-armv7"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-armv7"
platform = "armv7"
target = "armv7a-none-eabi"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-board-meta = { workspace = true }
fstart-driver-pl011 = { workspace = true }

serde_json = { workspace = true }

[[bin]]
name = "fstart-board-metadata"
path = "src/bin/fstart-board-metadata.rs"

