[package]
name = "fstart-board-qemu-armv7"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-armv7"
platform = "armv7"
target = "armv7a-none-eabi"
stage-package = "fstart-board-qemu-armv7-stage"
stage-bin = "fstart-stage"

[dependencies]
fstart-board-qemu-armv7-facts = { path = "facts" }
fstart-types = { workspace = true, features = ["std"] }
