[package]
name = "fstart-board-sifive-unmatched-hw-stage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
riscv64 = ["fstart-stage/riscv64"]
fu740-prci = ["fstart-stage/fu740-prci"]
fu740-ddr = ["fstart-stage/fu740-ddr"]
sifive-uart = ["fstart-stage/sifive-uart"]
ffs = ["fstart-stage/ffs"]
ed25519 = ["fstart-stage/ed25519"]
sha2-digest = ["fstart-stage/sha2-digest"]
sha3-digest = ["fstart-stage/sha3-digest"]
lz4 = ["fstart-stage/lz4"]
fdt = ["fstart-stage/fdt"]
flow-profile-minimal = ["fstart-stage/flow-profile-minimal"]
flow-profile-linuxboot = ["fstart-stage/flow-profile-linuxboot"]
flow-profile-uefi = ["fstart-stage/flow-profile-uefi"]
flow-profile-multistage = ["fstart-stage/flow-profile-multistage"]

[dependencies]
fstart-board-sifive-unmatched-hw-facts = { path = "../facts" }
fstart-stage = { workspace = true }
fstart-stage-runtime = { workspace = true }
fstart-services = { workspace = true }
fstart-log = { workspace = true }
fstart-platform-riscv64 = { workspace = true }
fstart-driver-fu740-ddr = { workspace = true }
fstart-driver-fu740-prci = { workspace = true }
fstart-driver-sifive-uart = { workspace = true }
fstart-types = { workspace = true }
ufmt = { workspace = true }

[[bin]]
name = "fstart-stage"
path = "src/main.rs"
