[package]
name = "fstart-platform-intel"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
host = []
stage = [
  "dep:fstart-driver-uart",
  "dep:fstart-log",
  "dep:fstart-stage",
  "dep:fstart-arch",
  "dep:ufmt",
  "fstart-core/pci",
]
acpi = ["stage", "dep:fstart-acpi", "dep:fstart-arch", "fstart-driver-intel/acpi"]
mp = ["stage", "dep:fstart-arch"]
smbios = ["stage", "dep:fstart-acpi", "dep:fstart-arch"]

[dependencies]
fstart-core = { workspace = true }
fstart-pci = { workspace = true }
fstart-driver-intel = { workspace = true, features = ["ffs-vbt"] }
fstart-driver-uart = { workspace = true, optional = true }
fstart-acpi = { workspace = true, features = ["x86"], optional = true }
fstart-arch = { workspace = true, optional = true, features = ["x86_64"] }
fstart-log = { workspace = true, optional = true }
fstart-stage = { workspace = true, optional = true }
heapless = { workspace = true }
konst = { workspace = true }
serde = { workspace = true }
ufmt = { workspace = true, optional = true }
