//! AML ThermalZone construct.
//!
//! [`ThermalZone`] declares an ACPI thermal zone containing thermal
//! objects such as `_TMP` (current temperature), `_CRT` (critical
//! shutdown temperature), `_PSV` (passive cooling threshold), and
//! cooling device references.
//!
//! Note: `ThermalZone` is deprecated in ACPI 6.0+ in favor of `Device`
//! nodes with `_HID` "ACPI0004".  However, it remains universally
//! supported by all major OS ACPI implementations and is still
//! generated by production firmware (including coreboot).

extern crate alloc;

use alloc::vec::Vec;

use acpi_tables::aml::Path;
use acpi_tables::{Aml, AmlSink};

/// AML opcode constants.
const EXT_OP_PREFIX: u8 = 0x5B;
const THERMAL_ZONE_OP: u8 = 0x85;

/// AML `ThermalZone` object.
///
/// Declares a named thermal zone scope containing child objects.
/// The name must be a valid 4-character ACPI NameSeg (e.g., "TZ00").
///
/// # AML encoding
///
/// ```text
/// ExtOpPrefix (0x5B) ThermalZoneOp (0x85) PkgLength NameString ObjectList
/// ```
///
/// # Example
///
/// ```ignore
/// use fstart_acpi::ext::thermal_zone::ThermalZone;
/// use acpi_tables::aml::{Path, Name, Method, Return};
///
/// // _TMP method returning 3000 (300.0 K = 26.85 C in tenths of Kelvin)
/// let temp = 3000u32;
/// let ret = Return::new(&temp);
/// let tmp_method = Method::new("_TMP".into(), 0, false, vec![&ret]);
///
/// // Critical temperature: 373.15 K (100 C) = 3732 tenths of Kelvin
/// let crt_val = 3732u32;
/// let crt = Name::new("_CRT".into(), &crt_val);
///
/// let tz = ThermalZone::new("TZ00".into(), vec![&tmp_method, &crt]);
/// ```
pub struct ThermalZone<'a> {
    name: Path,
    children: Vec<&'a dyn Aml>,
}

impl<'a> ThermalZone<'a> {
    /// Create a ThermalZone with the given name and child objects.
    pub fn new(name: Path, children: Vec<&'a dyn Aml>) -> Self {
        Self { name, children }
    }
}

impl Aml for ThermalZone<'_> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        // Serialize name and children to temp buffers to measure size.
        let mut name_bytes = Vec::new();
        self.name.to_aml_bytes(&mut name_bytes);

        let mut child_bytes = Vec::new();
        for child in &self.children {
            child.to_aml_bytes(&mut child_bytes);
        }

        let content_len = name_bytes.len() + child_bytes.len();
        let pkg_len = crate::encode_pkg_length(content_len);

        sink.byte(EXT_OP_PREFIX);
        sink.byte(THERMAL_ZONE_OP);
        sink.vec(&pkg_len);
        sink.vec(&name_bytes);
        sink.vec(&child_bytes);
    }
}

#[cfg(test)]
mod tests {
    extern crate alloc;

    use alloc::vec;
    use alloc::vec::Vec;

    use super::*;
    use acpi_tables::aml::{Method, Name, Return};

    #[test]
    fn test_thermal_zone_basic() {
        let crt_val = 3732u32;
        let crt = Name::new("_CRT".into(), &crt_val);
        let tz = ThermalZone::new("TZ00".into(), vec![&crt]);

        let mut bytes = Vec::new();
        tz.to_aml_bytes(&mut bytes);

        // Starts with ExtOpPrefix + ThermalZoneOp
        assert_eq!(bytes[0], EXT_OP_PREFIX);
        assert_eq!(bytes[1], THERMAL_ZONE_OP);
        assert!(bytes.len() > 8);

        // Name "TZ00" should appear after PkgLength
        let name_pos = bytes.windows(4).position(|w| w == b"TZ00");
        assert!(name_pos.is_some(), "TZ00 name not found in AML output");
    }

    #[test]
    fn test_thermal_zone_with_method() {
        let temp = 3000u32;
        let ret = Return::new(&temp);
        let tmp_method = Method::new("_TMP".into(), 0, false, vec![&ret]);

        let tz = ThermalZone::new("TZ01".into(), vec![&tmp_method]);

        let mut bytes = Vec::new();
        tz.to_aml_bytes(&mut bytes);

        assert_eq!(bytes[0], EXT_OP_PREFIX);
        assert_eq!(bytes[1], THERMAL_ZONE_OP);

        // Should contain both "TZ01" and "_TMP" somewhere in the output.
        assert!(bytes.windows(4).any(|w| w == b"TZ01"));
        assert!(bytes.windows(4).any(|w| w == b"_TMP"));
    }

    #[test]
    fn test_thermal_zone_empty() {
        let tz = ThermalZone::new("TZ02".into(), vec![]);

        let mut bytes = Vec::new();
        tz.to_aml_bytes(&mut bytes);

        assert_eq!(bytes[0], EXT_OP_PREFIX);
        assert_eq!(bytes[1], THERMAL_ZONE_OP);
        // Should be: 2 (opcodes) + 1 (pkg_len for small) + 4 (name) = 7 bytes
        assert!(bytes.len() >= 7);
    }
}
