[package]
name = "fstart-driver-superio"
description = "SuperIO framework and chip descriptors"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
acpi = ["dep:fstart-acpi", "dep:fstart-acpi-macros"]

[dependencies]
fstart-acpi = { workspace = true, features = ["x86"], optional = true }
fstart-acpi-macros = { path = "../fstart-acpi-macros", optional = true }
fstart-log = { workspace = true }
fstart-core = { workspace = true }
heapless = { workspace = true }
serde = { workspace = true }
ufmt = { workspace = true }
