[package]
name = "fstart-board-qemu-armv7"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-armv7"
platform = "armv7"
target = "armv7a-none-eabi"
stage-bin = "fstart-stage"
stage-recipe = "qemu-virt-linux"
[features]
default = []
stage = [
  "dep:fstart-stage",
  "dep:fstart-services",
  "dep:fstart-platform-armv7",
  "dep:fstart-driver-pl011",
  "fstart-stage/ffs",
  "fstart-stage/fdt",
]

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-platform-armv7 = { workspace = true, optional = true }
fstart-driver-pl011 = { workspace = true, optional = true }
