[package]
name = "fstart-board-bananapi-m1"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "bananapi-m1"
platform = "armv7"
target = "armv7a-none-eabi"
stage-bin = "fstart-stage"
stage-recipe = "sunxi-mmc-linux"

[features]
default = []
stage = [
  "dep:fstart-stage",
  "dep:fstart-services",
  "dep:fstart-driver-ns16550",
  "dep:fstart-driver-sunxi-mmc",
  "dep:fstart-platform-armv7",
  "fstart-stage/sunxi",
  "fstart-stage/ns16550",
  "dep:fstart-driver-sunxi-ccu",
  "dep:fstart-driver-sunxi-a20-dramc",
]
ffs = ["stage", "fstart-stage/ffs"]

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-driver-ns16550 = { workspace = true, optional = true }
fstart-driver-sunxi-mmc = { workspace = true, optional = true }
fstart-platform-armv7 = { workspace = true, optional = true }
fstart-driver-sunxi-ccu = { workspace = true, optional = true }
fstart-driver-sunxi-a20-dramc = { workspace = true, optional = true }
