[package]
name = "fstart-boot"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
fit = ["dep:dtoolkit", "dep:heapless", "dep:fstart-crypto"]
crabefi = ["dep:crabefi"]
std = ["fit", "fstart-crypto?/all"]
sha2-digest = ["fit", "fstart-crypto?/sha2-digest"]
sha3-digest = ["fit", "fstart-crypto?/sha3-digest"]

[dependencies]
fstart-core = { workspace = true }
fstart-crypto = { workspace = true, optional = true }
dtoolkit = { workspace = true, optional = true }
heapless = { workspace = true, optional = true }
# Upstream split into a workspace; package `crabefi-core` keeps lib name `crabefi`.
crabefi = { package = "crabefi-core", git = "https://github.com/ArthurHeymans/CrabEFI.git", rev = "2ab071995b4c137e7b316a0cb965bb5762898221", default-features = false, optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
fstart-arch = { workspace = true, features = ["x86_64"] }

[dev-dependencies]
fstart-core = { workspace = true, features = ["std"] }
dtoolkit = { workspace = true, features = ["write"] }
