name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for now, eventually run pipeline on each commit

      - name: Install toolchain and tools
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy rustfmt

      - name: Install DTC
        run: |
          sudo apt-get update -qy
          sudo apt-get install device-tree-compiler

      - name: Check Code Formatting
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings 

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
