[package]
name = "fstart-board-qemu-riscv64"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-riscv64"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"

[dependencies]
fstart-types = { workspace = true, features = ["std"] }
fstart-codegen = { workspace = true }
fstart-board-qemu-virt = { workspace = true }
fstart-device-registry = { workspace = true, features = ["all-drivers"] }
heapless = { workspace = true }
ron = { workspace = true }
serde = { workspace = true, features = ["std"] }
