[package]
name = "fstart-board-qemu-riscv64"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.fstart]
board = "qemu-riscv64"
platform = "riscv64"
target = "riscv64gc-unknown-none-elf"
stage-bin = "fstart-stage"
stage-recipe = "qemu-virt-linux"
[features]
default = []
stage = [
  "dep:fstart-stage",
  "dep:fstart-services",
  "dep:fstart-platform-riscv64",
  "dep:fstart-driver-ns16550",
  "fstart-stage/ffs",
  "fstart-stage/fdt",
]

[dependencies]
fstart-types = { workspace = true }
fstart-stage = { workspace = true, optional = true }
fstart-services = { workspace = true, optional = true }
fstart-platform-riscv64 = { workspace = true, optional = true }
fstart-driver-ns16550 = { workspace = true, optional = true }
